### ISSUE TITLE
AndroidVideoDecoder: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by TBYSKY** [flutter-webrtc/flutter-webrtc#1060]
I get this error when I use vp9 svc

AndroidVideoDecoder: deliverDecodedFrame failed
2
E/org.webrtc.Logging( 3273): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 3273): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 3273): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
E/org.webrtc.Logging( 3273): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 3273): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:380)
E/org.webrtc.Logging( 3273): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:364)

* **Plugin version**: 0.9.4
* **OS**: 
* **OS version**:

**Comment by pannawatth** [comment]
Hi Im facing the same problem when I try to produce screen media with vp8.
When another device consumes that screen It will display a black screen with an error log

E/org.webrtc.Logging(32118): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging(32118): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging(32118): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging(32118):    at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging(32118):    at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
E/org.webrtc.Logging(32118):    at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:72)
E/org.webrtc.Logging(32118):    at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:380)
E/org.webrtc.Logging(32118):    at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:364)

Did you figured out how to solve this problem?

**Comment by badpaybad** [comment]
Cause I found that DefaultVideoDecoderFactory only work with software encoder for my devices rk3288, hope this help

Go to file MethodCallHandlerImpl.java

In this function 
private void ensureInitialized() 

`
    DunpDefaultVideoDecoderFactory vidDecoder=new DunpDefaultVideoDecoderFactory(eglContext);

    mFactory = PeerConnectionFactory.builder()
            .setOptions(new Options())
            .setVideoEncoderFactory(vidEncoder)
            //.setVideoEncoderFactory(new org.webrtc.SoftwareVideoEncoderFactory())
            .setVideoDecoderFactory(vidDecoder)
            .setAudioDeviceModule(audioDeviceModule)
            .createPeerConnectionFactory();
`

You create similar class DunpDefaultVideoDecoderFactory

`
public class DunpDefaultVideoDecoderFactory implements VideoDecoderFactory {
    private final VideoDecoderFactory hardwareVideoDecoderFactory;
    private final VideoDecoderFactory softwareVideoDecoderFactory = new SoftwareVideoDecoderFactory();
    @Nullable
    private final VideoDecoderFactory platformSoftwareVideoDecoderFactory;

    public DunpDefaultVideoDecoderFactory(@Nullable EglBase.Context eglContext) {
        this.hardwareVideoDecoderFactory = new HardwareVideoDecoderFactory(eglContext);
        this.platformSoftwareVideoDecoderFactory = new PlatformSoftwareVideoDecoderFactory(eglContext);
    }

    DunpDefaultVideoDecoderFactory(VideoDecoderFactory hardwareVideoDecoderFactory) {
        this.hardwareVideoDecoderFactory = hardwareVideoDecoderFactory;
        this.platformSoftwareVideoDecoderFactory = null;
    }

    @Nullable
    public VideoDecoder createDecoder(VideoCodecInfo codecType) {
        VideoDecoder softwareDecoder = this.softwareVideoDecoderFactory.createDecoder(codecType);

        if (softwareDecoder != null) {
            Log.i("dunp", "dunp----------------------- softwareDecoder NOT null");
            return softwareDecoder;
        }

        if (softwareDecoder == null && this.platformSoftwareVideoDecoderFactory != null) {
            softwareDecoder = this.platformSoftwareVideoDecoderFactory.createDecoder(codecType);
        }

        if (softwareDecoder != null) {
            Log.i("dunp", "dunp----------------------- softwareDecoderPlatform NOT null");
            return softwareDecoder;
        }

        VideoDecoder hardwareDecoder = this.hardwareVideoDecoderFactory.createDecoder(codecType);

        if (hardwareDecoder != null) {
            Log.i("dunp", "dunp----------------------- hardwareDecoder NOT null");
            return softwareDecoder;
        }

        if (hardwareDecoder != null && softwareDecoder != null) {
            return new VideoDecoderFallback(softwareDecoder, hardwareDecoder);
        } else {
            return hardwareDecoder != null ? hardwareDecoder : softwareDecoder;
        }
    }

    public VideoCodecInfo[] getSupportedCodecs() {
        LinkedHashSet<VideoCodecInfo> supportedCodecInfos = new LinkedHashSet();
        supportedCodecInfos.addAll(Arrays.asList(this.softwareVideoDecoderFactory.getSupportedCodecs()));
        supportedCodecInfos.addAll(Arrays.asList(this.hardwareVideoDecoderFactory.getSupportedCodecs()));
        if (this.platformSoftwareVideoDecoderFactory != null) {
            supportedCodecInfos.addAll(Arrays.asList(this.platformSoftwareVideoDecoderFactory.getSupportedCodecs()));
        }

        return (VideoCodecInfo[]) supportedCodecInfos.toArray(new VideoCodecInfo[supportedCodecInfos.size()]);
    }
}
`
