### ISSUE TITLE
windows 11 Screen Shareing Filed

### ISSUE THREAD

**Issue by timmy-gzw** [flutter-webrtc/flutter-webrtc#1085]
When I want to use [flutter-webrtc-demo](https://github.com/flutter-webrtc/flutter-webrtc-demo) and [flutter-webrtc-server](https://github.com/flutter-webrtc/flutter-webrtc-server) to start screen sharing on windows 11, the console prompts an exception, does it not support windows11?

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to getDisplayMedia: source not found!
#0      MediaDeviceNative.getDisplayMedia (package:flutter_webrtc/src/native/mediadevices_impl.dart:68:7)
<asynchronous suspension>
#1      Signaling.createStream (package:flutter_webrtc_demo/src/call_sample/signaling.dart:324:11)
<asynchronous suspension>
#2      Signaling._createSession (package:flutter_webrtc_demo/src/call_sample/signaling.dart:337:22)
<asynchronous suspension>
#3      Signaling.invite (package:flutter_webrtc_demo/src/call_sample/signaling.dart:112:23)
<asynchronous suspension>
```

**Comment by Mamena2020** [comment]
any update of this? 
i'am using Windows 10 Education 64-bit (10.0, Build 19042)

got error
```
Unable to getDisplayMedia: source not found
```

**Comment by obansa** [comment]
I also faced this issue.
For me, the problem is not from the OS. when you want to share screen in other platform, a dialog normally pops up were you select which screen to share. Desktop apps does not have that functionality. so either you add the dialog manually or select the screen you want to share 

```
List<DesktopCapturerSource> sources = await desktopCapturer
        .getSources(types: [SourceType.Screen, SourceType.Window]);
    
    print(sources.first.name);

    var stream = await navigator.mediaDevices
        .getDisplayMedia({
      'audio': true,
      'video': {'deviceId': {'exact': sources.first.id},
      }
    });
```

**Comment by umer-ilyas** [comment]
> I also faced this issue. For me, the problem is not from the OS. when you want to share screen in other platform, a dialog normally pops up were you select which screen to share. Desktop apps does not have that functionality. so either you add the dialog manually or select the screen you want to share
> 
> ```
> List<DesktopCapturerSource> sources = await desktopCapturer
>         .getSources(types: [SourceType.Screen, SourceType.Window]);
>     
>     print(sources.first.name);
> 
>     var stream = await navigator.mediaDevices
>         .getDisplayMedia({
>       'audio': true,
>       'video': {'deviceId': {'exact': sources.first.id},
>       }
>     });
> ```

This works for me on flutter for windows app
