### ISSUE TITLE
MissingPluginException(No implementation found for method createVideoRenderer on channel FlutterWebRTC.Method)

### ISSUE THREAD

**Issue by Snooker-shoot** [flutter-webrtc/flutter-webrtc#1155]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method createVideoRenderer on channel FlutterWebRTC.Method)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      RTCVideoRenderer.initialize (package:flutter_webrtc/src/native/rtc_video_renderer_impl.dart:23:22)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      _WebRTCStreamingPlayer.start (package:flutterplayer/main.dart:77:5)
                                                                                                    <asynchronous suspension>

**Comment by Snooker-shoot** [comment]
在fragment里嵌入就不报这个错，大佬们赶紧帮忙解决一下

**Comment by cloudwebrtc** [comment]
如果是flutter嵌入模式，确认一下有没有正确注册插件？
https://github.com/flutter-webrtc/flutter-webrtc/blob/main/android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java#L50

**Comment by Snooker-shoot** [comment]
这个在哪注册？是调用public static void registerWith(Registrar registrar)这个方法注册吗？Registrar东西从哪获取？有详细一点的使用教程吗？ @cloudwebrtc
