### ISSUE TITLE
Linux fatal error when building

### ISSUE THREAD

**Issue by krillefear** [flutter-webrtc/flutter-webrtc#1212]
**Describe the bug**

When building on Linux I get this error:

```sh
[  +96 ms] Building Linux application... (completed in 6.1s)
[  +26 ms] (fluffychat:230187): Gtk-WARNING **: 20:33:18.576: Locale not supported by C library.
[        ]      Using the fallback 'C' locale.
[ +131 ms] #
[        ] # Fatal error in: ../../media/engine/adm_helpers.cc, line 39
[        ] # last system error: 0
[        ] # Check failed: 0 == adm->Init() (0 vs. -1)
[  +84 ms] # Failed to initialize the ADM.
[   +2 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +1 ms] Error launching application on Linux.
```

**To Reproduce**

Build on Ubuntu 22.10 with Flutter 3.3.9

**Expected behavior**

Just builds

**Platform information**

* **Flutter version**: 3.3.9
* **Plugin version**: 0.9.18
* **OS**:  Ubuntu
* **OS version**: 22.10

**Comment by cloudwebrtc** [comment]
The installation of snap will cause the libwebrtc link of flutter-webrtc to fail due to the inconsistent glibc version. You can try to manually install the flutter sdk, which can compile and run normally.

https://docs.flutter.dev/get-started/install/linux#install-flutter-manually

**Comment by krillefear** [comment]
No, I'm using the Flutter version from flutter.dev directly

**Comment by cloudwebrtc** [comment]
Can you try running `flutter run -d linux -v` and observe the log output?

**Comment by cloudwebrtc** [comment]
From the log, it seems that the runtime failed, which is related to the failure to initialize the audio device module.
```
[        ] # Fatal error in: ../../media/engine/adm_helpers.cc, line 39
[        ] # last system error: 0
[        ] # Check failed: 0 == adm->Init() (0 vs. -1)
[  +84 ms] # Failed to initialize the ADM.
```

**Comment by krillefear** [comment]
> Can you try running `flutter run -d linux -v` and observe the log output?



```sh
[        ] -- Installing: /home/krille/HADTF/Flutter/fluffychat/build/linux/x64/debug/bundle/data/flutter_assets/shaders
[        ] -- Installing: /home/krille/HADTF/Flutter/fluffychat/build/linux/x64/debug/bundle/data/flutter_assets/shaders/ink_sparkle.frag
[        ] -- Installing: /home/krille/HADTF/Flutter/fluffychat/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/krille/HADTF/Flutter/fluffychat/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[ +108 ms] Building Linux application... (completed in 29.0s)
[  +22 ms] (fluffychat:73758): Gtk-WARNING **: 15:15:42.860: Locale not supported by C library.
[        ]      Using the fallback 'C' locale.
[ +117 ms] #
[        ] # Fatal error in: ../../media/engine/adm_helpers.cc, line 39
[        ] # last system error: 0
[        ] # Check failed: 0 == adm->Init() (0 vs. -1)
[  +82 ms] # Failed to initialize the ADM.
[   +2 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +1 ms] Error launching application on Linux.
[   +2 ms] "flutter run" took 30,530ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +218 ms] ensureAnalyticsSent: 217ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by gev** [comment]
> From the log, it seems that the runtime failed, which is related to the failure to initialize the audio device module.
> 
> ```
> [        ] # Fatal error in: ../../media/engine/adm_helpers.cc, line 39
> [        ] # last system error: 0
> [        ] # Check failed: 0 == adm->Init() (0 vs. -1)
> [  +84 ms] # Failed to initialize the ADM.
> ```

Have the same error only when start app from console via xinit:

```
sudo xinit /home/pi/webrtc/build/linux/.../webrtc
```

When start on desktop all works as well:
![telegram-cloud-photo-size-2-5357137396229064480-y](https://user-images.githubusercontent.com/919914/213796365-4480ef6b-7533-465a-b04a-7c6279fdd2b7.jpg)

**Comment by cloudwebrtc** [comment]
Looks like you have flutter-webrtc running on raspberry pi, looks cool ;)

**Comment by cloudwebrtc** [comment]
hey @krille-chan, Have you tried the latest main branch? I test on ubuntu x64/arm64 20.04 and it works correctly, use the latest official flutter SDK or flutter SDK from snap

**Comment by krille-chan** [comment]
Will try it out soon :)

**Comment by krille-chan** [comment]
Now it builds but it does not start. When trying to start the snap version I have this error:

```
/snap/fluffychat/556/bin/fluffychat: error while loading shared libraries: libwebrtc.so: cannot open shared object file: No such file or directory
```

**Comment by krille-chan** [comment]
While it's weird. I can find /snap/fluffychat/current/bin/lib/libwebrtc.so in the snap libraries...

**Comment by cloudwebrtc** [comment]
It looks like the problem happens with snapcraft compiled app?
Using flutter run should work correctly (flutter sdk install form snap),

**Comment by cloudwebrtc** [comment]
This looks like rpath linking issue for libwebrtc.so, let me see how to fix

**Comment by KoiFresh** [comment]
> Now it builds but it does not start. When trying to start the snap version I have this error:
> 
> ```
> /snap/fluffychat/556/bin/fluffychat: error while loading shared libraries: libwebrtc.so: cannot open shared object file: No such file or directory
> ```


Hi, in my case I could fix the error by adding the directory of the `libwebrtc.so` file to `LD_LIBRARY_PATH` environment variable

in my `snapcraft.yaml` it looks like this:
```yaml
apps:
  <app name>:
    ...
    environment:
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/bin/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
```

**Comment by krille-chan** [comment]
@KoiFresh Thank you so much. I will try it out :)

**Comment by KoiFresh** [comment]
@cloudwebrtc it is indeed a rpath issue. I did some research and it looks like `libflutter_webrtc.so` ins't able to find the precompiled `libwebrtc.so` as soon as the bundle is distributed to a non development system (no source, no flutter), but if you are running on the dev system everything works fine.
I just inspected the compiled binaries to find out where this behavior comes from.

So as first step lets take a look where the compiled binary finds the `libwebrtc.so file:
```bash
ldd ./build/linux/arm64/release/bundle/flutter_webrtc_example
```
from the result:
```bash
…
libflutter_webrtc_plugin.so => /home/ubuntu/flutter-webrtc/example/build/linux/arm64/release/bundle/lib/libflutter_webrtc_plugin.so (0x0000ffffa5b10000)
libflutter_linux_gtk.so => /home/ubuntu/flutter-webrtc/example/build/linux/arm64/release/bundle/lib/libflutter_linux_gtk.so (0x0000ffffa4d90000)
…
libwebrtc.so => /home/ubuntu/flutter-webrtc/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/../third_party/libwebrtc/lib/linux-arm64/libwebrtc.so (0x0000ffffa28a0000)
…
```
As we can see the `libflutter_webrtc_plugin.so` (actual flutter plugin) comes from the lib folder inside the bundle, but the `libwebrtc.so` is not found 
inside the lib folder but in the development folder at
`third_party/libwebrc/linux-arm64/libwebrtc.so`. This is clearly not the location where we want to load the library form, cause this only exists during development.

To find the reason why the library is loaded from the wrong place we take a look at the RUNPATH value of the binaries with readelf.
First lets find the RUNPATH of the executable:
```bash
readelf -d build/linux/arm64/release/bundle/flutter_webrtc_example
```
output:
```bash
…
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/lib]
…
```
So libs can be loaded from $ORIGIN/lib ($ORIGIN => location of the file), 
this is fine. `flutter_webrtc_example` is loading `libflutter_webrtc_plugin.
so` from there. Lets go on and take a look at `flutter_webrtc_plugin.so`:
```bash
readelf -d build/linux/arm64/release/bundle/lib/libflutter_webrtc_plugin.so 
```
output:
```bash
…
 0x000000000000001d (RUNPATH)            Library runpath: [/home/ubuntu/flutter-webrtc/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/../third_party/libwebrtc/lib/linux-arm64:/home/ubuntu/flutter-webrtc/example/linux/flutter/ephemeral]
…
```
So here we doesn't have anything install location dependent, we just have the paths used by `flutter run` during development and because `flutter_webrtc_example` loads `libflutter_webrtc_plugin.so` and `libflutter_webrtc_plugin.so` actually loads `libwebrtc.so` the library will not be taken form the libs folder but from the third_party folder, which will not exist after distribution.

So in order for `libflutter_webrtc_plugin.so` to find `libwebrtc.so` located 
next to it, it has to look the directory where it is located.

One possibility is to set LD_LIBRARY_PATH to that directory, so if a library is not found in RUNPATH it will be searched on all paths in LD_LIBRARY_PATH.
Another possibility would be to modify /etc/ld.so.conf as described here #1241
Or we could modify the CMakeLists file of the plugin, so that $ORIGIN is added to the RUNPATH for `libflutter_webrtc_plugin.so`.

I have also submitted a PR for that #1398.

if we now look where ldd finds the library's:
```bash
…
libflutter_webrtc_plugin.so => /home/ubuntu/flutter-webrtc/example/build/linux/arm64/release/bundle/lib/libflutter_webrtc_plugin.so (0x0000ffffb39c0000)
libflutter_linux_gtk.so => /home/ubuntu/flutter-webrtc/example/build/linux/arm64/release/bundle/lib/libflutter_linux_gtk.so (0x0000ffffb2c40000)
…
libwebrtc.so => /home/ubuntu/flutter-webrtc/example/build/linux/arm64/release/bundle/lib/libwebrtc.so
…
```
`libwebrtc.so` is found in the libs folder where `libflutter_webrtc_plugin.so` is located.

and the output from readelf:
```bash
...
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:/home/ubuntu/flutter-webrtc/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/../third_party/libwebrtc/lib/linux-arm64:/home/ubuntu/flutter-webrtc/example/linux/flutter/ephemeral]
...
```

I hope the above points out, why `libwebrtc.so` can't be found inside snaps, 
or on non dev systems.

see also:
https://stackoverflow.com/questions/47117443/dynamic-linking-with-rpath-not-working-under-ubuntu-17-10/47243544#47243544
https://www.qt.io/blog/2011/10/28/rpath-and-runpath
https://cmake.org/cmake/help/latest/prop_tgt/BUILD_RPATH.html
