### ISSUE TITLE
NoClassDefFoundError for Android 5

### ISSUE THREAD

**Issue by njovy** [flutter-webrtc/flutter-webrtc#1261]
**Describe the bug**

```
Fatal Exception: java.lang.NoClassDefFoundError: com.twilio.audioswitch.scanners.AudioDeviceScanner
       at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.kt:87)
       at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.kt:53)
       at com.cloudwebrtc.webrtc.audio.AudioSwitchManager.lambda$initAudioSwitch$2(AudioSwitchManager.java:68)
       at com.cloudwebrtc.webrtc.audio.AudioSwitchManager.$r8$lambda$qrxuqTWNaYXJVmp84oOkK5ndL6w(AudioSwitchManager.java)
       at com.cloudwebrtc.webrtc.audio.AudioSwitchManager$$InternalSyntheticLambda$0$0c70b57a6e87f8ff5fd479c54ab108bb2c55d8c38fd322d12b441ee422642c4b$0.run(AudioSwitchManager.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:7007)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

Above is the stack trace that I received on Crashlytics. I updated flutter-webrtc to version 0.9.21 and since then, I have been encountering this exception.

**To Reproduce**
Run a flutter webrtc demo on Android 5

**Expected behavior**
Should run

**Platform information**

* **Flutter version**: 3.7.2
* **Plugin version**: 0.9.21
* **OS**: Android
* **OS version**: Android 5 (SDK 21)

**Comment by huyvoduc** [comment]
I got the same issue, the app crash immediately on launch, please help us to fix this critical bug 

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xyz.be.driver, PID: 4657
    java.lang.NoClassDefFoundError: com.twilio.audioswitch.scanners.AudioDeviceScanner
        at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.kt:87)
        at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.kt:53)
        at com.cloudwebrtc.webrtc.audio.AudioSwitchManager.lambda$initAudioSwitch$2$com-cloudwebrtc-webrtc-audio-AudioSwitchManager(AudioSwitchManager.java:68)
        at com.cloudwebrtc.webrtc.audio.AudioSwitchManager$$ExternalSyntheticLambda1.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Platform information**

- Flutter version: 3.0.5
- Plugin version: 0.9.23
- OS: Android
- OS version: Android 5.1 (SDK 22)

**Comment by cloudwebrtc** [comment]
After investigating and reproducing this issue on an Android 5.0 emulator, AudioSwitch does not support `Build.VERSION_CODES.M` below API Level 23, so (an Android 6.0) or above device is the minimum requirement (unless someone makes a patch for API 21 versions of AudioDeviceScanner), I will close this issue.
<img width="936" alt="image" src="https://user-images.githubusercontent.com/17733746/221510355-d81b2893-b50c-405d-a531-5b98563f4a8e.png">

**Comment by tkortekaas** [comment]
Any updates on this issue? I am still having it today
