### ISSUE TITLE
Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference

### ISSUE THREAD

**Issue by Techno-Disaster** [flutter-webrtc/flutter-webrtc#1339]
Facing this since 0.9.25 on calls when a app is terminated

```
E/AndroidRuntime(26459): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
E/AndroidRuntime(26459):        at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserAudio(GetUserMediaImpl.java:354)
E/AndroidRuntime(26459):        at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:595)
E/AndroidRuntime(26459):        at com.cloudwebrtc.webrtc.GetUserMediaImpl.access$000(GetUserMediaImpl.java:84)
E/AndroidRuntime(26459):        at com.cloudwebrtc.webrtc.GetUserMediaImpl$1.invoke(GetUserMediaImpl.java:456)
E/AndroidRuntime(26459):        at com.cloudwebrtc.webrtc.GetUserMediaImpl.lambda$requestPermissions$0(GetUserMediaImpl.java:841)
E/AndroidRuntime(26459):        at com.cloudwebrtc.webrtc.GetUserMediaImpl$$ExternalSyntheticLambda0.invoke(Unknown Source:6)
E/AndroidRuntime(26459):        at com.cloudwebrtc.webrtc.utils.PermissionUtils$1.onReceiveResult(PermissionUtils.java:115)
E/AndroidRuntime(26459):        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime(26459):        at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(26459):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26459):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(26459):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(26459):        at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(26459):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26459):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(26459):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by Techno-Disaster** [comment]
c662c892b751ab63bb95d837151273d1c5e87c69
