### ISSUE TITLE
Crash happened in video room

### ISSUE THREAD

**Issue by wanchao-xu** [flutter-webrtc/flutter-webrtc#1342]
**Describe the bug**
[flutter_janus_client](https://github.com/flutterjanus/flutter_janus_client) use flutter-webrtc plugin, and it support video room funcation. A device join in video room and video room has more than one participator, close connection of the device, crash happened.

**To Reproduce**
It need more than one device to reproduce the crash bug
1. Run example of flutter_janus_client on linux, and join in a video room.
2. Run another example and join in the same video room.
3. Hang up the connection, the crash happened.

I analysed the peer connection
```
void FlutterPeerConnection::RTCPeerConnectionClose(
    RTCPeerConnection* pc, const std::string& uuid,
    std::unique_ptr<MethodResultProxy> result) {
  pc->Close();
  result->Success();
}

void FlutterPeerConnection::RTCPeerConnectionDispose(
    RTCPeerConnection* pc, const std::string& uuid,
    std::unique_ptr<MethodResultProxy> result) {
  auto it = base_->peerconnection_observers_.find(uuid);
  if (it != base_->peerconnection_observers_.end())
    base_->peerconnection_observers_.erase(it);
  auto it2 = base_->peerconnections_.find(uuid);
  if (it2 != base_->peerconnections_.end()) base_->peerconnections_.erase(it2);
  result->Success();
}
```

when hang up connection, peer connection call close first, then call dispose. Sometimes server send a setRemoteDescription request to peer connection after RTCPeerConnectionClose(before RTCPeerConnectionDispose), and peer connection can be found because it is not removed from the `base_->peerconnections_`, the crash will be happened.

Here is core dump by gdb
```
Thread 1 "example" received signal SIGSEGV, Segmentation fault.
0x00007ffff3589a5e in libwebrtc::RTCPeerConnectionImpl::SetLocalDescription(portable::string, portable::string, fixed_size_function<void (), 128ul, (construct_type)3>, fixed_size_function<void (char const*), 128ul, (construct_type)3>) ()
   from /home/xuwc/work/flutter_janus_client/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/../third_party/libwebrtc/lib/linux-x64/libwebrtc.so
(gdb) bt full
#0  0x00007ffff3589a5e in libwebrtc::RTCPeerConnectionImpl::SetLocalDescription(portable::string, portable::string, fixed_size_function<void (), 128ul, (construct_type)3>, fixed_size_function<void (char const*), 128ul, (construct_type)3>) ()
    at /home/xuwc/work/flutter_janus_client/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/../third_party/libwebrtc/lib/linux-x64/libwebrtc.so
#1  0x00007ffff7ee8dcb in flutter_webrtc_plugin::FlutterPeerConnection::SetLocalDescription(libwebrtc::RTCSessionDescription*, libwebrtc::RTCPeerConnection*, std::unique_ptr<MethodResultProxy, std::default_delete<MethodResultProxy> >) (this=0xb92100, sdp=0x7fffc4506630, pc=0x7fffc4346010, result=...)
    at /home/xuwc/work/flutter_janus_client/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/common/cpp/src/flutter_peerconnection.cc:319
        result_ptr = warning: RTTI symbol not found for class 'std::_Sp_counted_ptr<MethodResultProxy*, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr<MethodResultProxy*, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<class MethodResultProxy> (use count 7, weak count 0) = {get() = 0x1136210}
#2  0x00007ffff7f29851 in flutter_webrtc_plugin::FlutterWebRTC::HandleMethodCall(MethodCallProxy const&, std::unique_ptr<MethodResultProxy, std::default_delete<MethodResultProxy> >) (this=0xb918b0, method_call=..., result=std::unique_ptr<class MethodResultProxy> = {...})
    at /home/xuwc/work/flutter_janus_client/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/common/cpp/src/flutter_webrtc.cc:222
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
        params = std::map with 2 elements
        peerConnectionId = <incomplete type>
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
        constraints = std::map with 2 elements
        pc = 0x7fffc4346010
        error = 
            {line = {m_buf = "\000\242F\000\000\000\000\000\033\364\225\362\377\177\000\000\001\000\000\000\000\000\000\000\000\005\000\000\320\002\000\000\000\242F", '\000' <repeats 12 times>, m_dynamic = 0x0, m_length = 0}, description = {m_buf = "\000\311\377\377\377\177\000\000\363\325k\364\377\177\000\000\360\335~\000\000\000\000\000\340\033\201\364\377\177\000\000\a\000\000\000\000\000\000\000NF\205\000\000\000\000", m_dynamic = 0x0, m_length = 0}}
        description = {ptr_ = 0x7fffc4506630}
#3  0x00007ffff7f4f4c0 in flutter_webrtc_plugin::FlutterWebRTCPluginImpl::HandleMethodCall(flutter::MethodCall<flutter::EncodableValue> const&, std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>, std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >) (this=0x98f890, 
    method_call=..., result=std::unique_ptr<class flutter::MethodResult<flutter::EncodableValue>> = {...})
    at /home/xuwc/work/flutter_janus_client/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/common/cpp/flutter_webrtc_plugin.cc:55
        method_call_proxy = std::unique_ptr<class MethodCallProxy> = {get() = 0x12308e0}
#4  0x00007ffff7f4f3cf in flutter_webrtc_plugin::FlutterWebRTCPluginImpl::RegisterWithRegistrar(flutter::PluginRegistrar*)::{lambda(auto:1 const&, auto:2)#1}::operator()<flutter::MethodCall<flutter::EncodableValue>, std::unique_ptr<flutter::MethodResult<flutter::MethodCall>, std::default_delete<flutter::MethodResult> > >(flutter::MethodCall<flutter::EncodableValue> const&, std::unique_ptr<flutter::MethodResult<flutter::MethodCall>, std::default_delete<flutter::MethodResult> >) const (this=0xb9a9d0, call=..., result=...)
    at /home/xuwc/work/flutter_janus_client/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/common/cpp/flutter_webrtc_plugin.cc:28
#5  0x00007ffff7f4f23b in std::_Function_handler<void (flutter::MethodCall<flutter::EncodableValue> const&, std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>, std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >), flutter_webrtc_plugin::FlutterWebRTCPluginImpl::RegisterWithRegistrar(flutter::PluginRegistrar*)::{lambda(auto:1 const&, auto:2)#1}>::_M_invoke(std::_Any_data const&, flutter::MethodCall<flutter::EncodableValue> const&, std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>, std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >&&)
    (__functor=..., __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#6  0x00007ffff7f4e0d0 in std::function<void (flutter::MethodCall<flutter::EncodableValue> const&, std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>, std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >)>::operator()(flutter::MethodCall<flutter::EncodableValue> const&, std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>, std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >) const
    (this=0xb9a9d0, __args=..., __args=std::unique_ptr<class flutter::MethodResult<flutter::EncodableValue>> = {...})
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#7  0x00007ffff7f4dec9 in flutter::MethodChannel<flutter::EncodableValue>::SetMethodCallHandler(std::function<void (flutter::MethodCall<flutter::EncodableValue> const&, std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>, std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >)>) const::{lambda(unsigned char const*, unsigned long, std::function<void (unsigned char const*, unsigned long)>)#1}::operator()(unsigned char const*, unsigned long, std::function<void (unsigned char const*, unsigned long)>) const
    (this=0xb9a9d0, message=0xa689d0 "\a\023setLocalDescription\r\002\a\020peerConnectionId\a$391C4889-7C78-4862-BA08-6A76850D2829\a\vdescription\r\002\a\003sdp\a\376\213\005v=0\r\no=- 6827669665817755274 3 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=extmap-allow-m"..., message_size=1536, reply=...)
    at /home/xuwc/work/flutter_janus_client/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/flutter/include/flutter/method_channel.h:119
        result = std::unique_ptr<class flutter::EngineMethodResult<flutter::EncodableValue>> = {get() = 0x0}
        method_call = std::unique_ptr<class flutter::MethodCall<flutter::EncodableValue>> = {get() = 0x11fbc20}
#8  0x00007ffff7f4daa6 in std::_Function_handler<void (unsigned char const*, unsigned long, std::function<void (unsigned char const*, unsigned long)>), flutter::MethodChannel<flutter::EncodableValue>::SetMethodCallHandler(std::function<void (flutter::MethodCall<flutter::EncodableValue> const&, std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>, std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >)>) const::{lambda(unsigned char const*, unsigned long, std::function<void (unsigned char const*, unsigned long)>)#1}>::_M_invoke(std::_Any_data const&, unsigned char const*&&, unsigned long&&, std::function<void (unsigned char const*, unsigned long)>&&)
```

Why not remove peer connection form `base_->peerconnections` in `RTCPeerConnectionClose`?

**Expected behavior**
Crash should be not happened.

**Platform information**
Linux

* **Flutter version**: 
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by cloudwebrtc** [comment]
@wanchao-xu need to cut a new release for this fix?

**Comment by wanchao-xu** [comment]
> @wanchao-xu need to cut a new release for this fix?

No, just merge it to main branch.
