### ISSUE TITLE
crash android when using sourceId in video Constraints on android lower than sdk 26

### ISSUE THREAD

**Issue by MohsenHaydari** [flutter-webrtc/flutter-webrtc#1365]
hi. I use the 'optional: [{sourceId: 1}'' key for selecting video devices in media constraints, I used this option in some SDK versions. In some of these versions, the device crashes
SDK 33 ok
SDK 32 ok
SDK 26 ok

SDK 25 crash
SDK 23 crash

I think this problem applies to versions lower than 26

logging

```
java.lang.NullPointerException: Attempt to invoke interface method 'void org.webrtc.VideoCapturer.initialize(org.webrtc.SurfaceTextureHelper, android.content.Context, org.webrtc.CapturerObserver)' on a null object reference
E/AndroidRuntime( 5350): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserVideo(GetUserMediaImpl.java:730)
E/AndroidRuntime( 5350): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:597)
E/AndroidRuntime( 5350): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.access$000(GetUserMediaImpl.java:84)
E/AndroidRuntime( 5350): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl$1.invoke(GetUserMediaImpl.java:456)
E/AndroidRuntime( 5350): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.lambda$requestPermissions$1(GetUserMediaImpl.java:849)
E/AndroidRuntime( 5350): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass)
E/AndroidRuntime( 5350): 	at com.cloudwebrtc.webrtc.utils.PermissionUtils$1.onReceiveResult(PermissionUtils.java:115)
E/AndroidRuntime( 5350): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime( 5350): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 5350): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5350): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 5350): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/AndroidRuntime( 5350): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5350): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime( 5350): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```
Media Constraints object
```
{audio: {optional: [{sourceId: 0}]}, video: {optional: [{sourceId: 1}], width: 640, height: 480, frameRate: 30}}

```

**Comment by afl-dev** [comment]
also pixel 6 apli 34
