### ISSUE TITLE
webrtc screenshare crashes app

### ISSUE THREAD

**Issue by omofolarin** [flutter-webrtc/flutter-webrtc#1375]
**Describe the bug**
W/System.err( 9765): java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException
W/System.err( 9765): 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
W/System.err( 9765): 	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
W/System.err( 9765): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper.initEncode(SimulcastVideoEncoderFactoryWrapper.kt:111)
W/System.err( 9765): Caused by: java.lang.IllegalArgumentException
W/System.err( 9765): 	at android.media.MediaCodec.native_configure(Native Method)
W/System.err( 9765): 	at android.media.MediaCodec.configure(MediaCodec.java:2214)
W/System.err( 9765): 	at android.media.MediaCodec.configure(MediaCodec.java:2130)
W/System.err( 9765): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.configure(MediaCodecWrapperFactoryImpl.java:36)
W/System.err( 9765): 	at org.webrtc.HardwareVideoEncoder.initEncodeInternal(HardwareVideoEncoder.java:273)
W/System.err( 9765): 	at org.webrtc.HardwareVideoEncoder.initEncode(HardwareVideoEncoder.java:231)
W/System.err( 9765): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper.initEncode$lambda$0(SimulcastVideoEncoderFactoryWrapper.kt:109)
W/System.err( 9765): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper.$r8$lambda$4_8OOhnixrzHpnCh49psWgv_jfs(Unknown Source:0)
W/System.err( 9765): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$$ExternalSyntheticLambda10.call(Unknown Source:6)
W/System.err( 9765): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/System.err( 9765): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err( 9765): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err( 9765): 	at java.lang.Thread.run(Thread.java:1012)
E/rtc     ( 9765): #
**To Reproduce**

**Expected behavior**
```
    // Required for android screenshare.
        try {
          bool hasPermissions = await FlutterBackground.hasPermissions;
          if (!isRetry) {
            const androidConfig = FlutterBackgroundAndroidConfig(
              notificationTitle: 'Screen Sharing',
              notificationText: 'LiveKit Example is sharing the screen.',
              notificationImportance: AndroidNotificationImportance.Default,
              notificationIcon: AndroidResource(
                name: 'livekit_ic_launcher',
                defType: 'mipmap',
              ),
            );
            hasPermissions = await FlutterBackground.initialize(
              androidConfig: androidConfig,
            );
          }

          final isBackgroundExecutionEnabled =
              FlutterBackground.isBackgroundExecutionEnabled;

          if (hasPermissions && !isBackgroundExecutionEnabled) {
            await FlutterBackground.enableBackgroundExecution();
          }
        } catch (e) {
          if (!isRetry) {
            return await Future<void>.delayed(const Duration(seconds: 1),
                () => requestBackgroundPermission(true));
          }
          print('could not publish video: $e');
        }

  await widget.room.localParticipant?.setScreenShareEnabled(
          true,
          captureScreenAudio: true,
        );
        
  ```
**Platform information**

* **Flutter version**: 
Flutter (Channel stable, 3.10.3, on macOS 13.3.1 22E772610a darwin-x64, locale en-NG
* **Plugin version**:
flutter_webrtc: ^0.9.33
* **OS**: 
Android
* **OS version**:
Android 13

**Comment by shivanshtalwar0** [comment]
Check #1379

**Comment by shivanshtalwar0** [comment]
look at this example https://github.com/flutterjanus/screenshare_example

**Comment by sagartargeticon** [comment]
@shivanshtalwar0 in this example I am not able to screen sharing in PIP mode
