### ISSUE TITLE
`MediaRecorder` is not working

### ISSUE THREAD

**Issue by HosamHasanRamadan** [flutter-webrtc/flutter-webrtc#1405]
**Describe the bug**
`MediaRecorder` doesn't work it just creates empty file , when i stop recording the app crashes
Logs when start recording:
```log
W/OMXUtils(30168): do not know color format 0x7f000200 = 2130706944
W/OMXUtils(30168): do not know color format 0x7f000789 = 2130708361
I/MtkACodec(30168): setMTKParameters, width: 720
I/MtkACodec(30168): setMTKParameters, height: 1280
I/ACodec_roi(30168): + setRoiParameters 239
I/ACodec_roi(30168): - setRoiParameters 245
I/ACodec  (30168): setupAVCEncoderParameters with [profile: High] [level: Level41]
I/ACodec  (30168): [OMX.MTK.VIDEO.ENCODER.AVC] cannot encode color aspects. Ignoring.
I/ACodec  (30168): [OMX.MTK.VIDEO.ENCODER.AVC] cannot encode HDR static metadata. Ignoring.
I/ACodec  (30168): setupVideoEncoder succeeded
I/MtkACodec(30168): setMTKParameters, width: 720
I/MtkACodec(30168): setMTKParameters, height: 1280
I/ACodec_roi(30168): + setRoiParameters 239
I/ACodec_roi(30168): - setRoiParameters 245
W/OMXUtils(30168): do not know color format 0x7f000789 = 2130708361
I/org.webrtc.Logging(30168): EglBase14Impl: Using OpenGL ES version 2
I/BufferQueueProducer(30168): [SurfaceTexture-1-30168-0](this:0x78867b1800,id:0,api:4,p:571,c:30168) queueBuffer: slot 6 is dropped, handle=0x780eef7a00
W/H2BGraphicBufferProducer(30168): getConsumerUsage is not fully supported
E/GraphicExt(30168): GraphicExtModuleLoader::CreateGraphicExtInstance false
D/Surface (30168): Surface::connect(this=0x788697f000,api=1)
E/IMGSRV  (30168): :0: ScheduleTA: Skipping render from different gc/thread!
```

Crash when stop recording:
```log
D/Surface (30168): Surface::disconnect(this=0x788697f000,api=1)
E/AndroidRuntime(30168): FATAL EXCEPTION: VideoFileRendererRenderThread
E/AndroidRuntime(30168): Process: com.example.live_audio_stream_webrtc, PID: 30168
E/AndroidRuntime(30168): java.lang.IllegalStateException: Can't stop due to wrong state.
E/AndroidRuntime(30168): 	at android.media.MediaMuxer.stop(MediaMuxer.java:469)
E/AndroidRuntime(30168): 	at com.cloudwebrtc.webrtc.record.VideoFileRenderer.lambda$release$3$com-cloudwebrtc-webrtc-record-VideoFileRenderer(VideoFileRenderer.java:146)
E/AndroidRuntime(30168): 	at com.cloudwebrtc.webrtc.record.VideoFileRenderer$$ExternalSyntheticLambda2.run(Unknown Source:2)
E/AndroidRuntime(30168): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(30168): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(30168): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(30168): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/Process (30168): Sending signal. PID: 30168 SIG: 9
```
**To Reproduce**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'package:path_provider/path_provider.dart';

class MediaRecordingIssuePage extends StatefulWidget {
  const MediaRecordingIssuePage({super.key});

  @override
  State<MediaRecordingIssuePage> createState() => _MediaRecordingIssuePageState();
}

class _MediaRecordingIssuePageState extends State<MediaRecordingIssuePage> {
  final notifier = PageNotifier();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Center(
        child: AnimatedBuilder(
          animation: notifier,
          builder: (context, child) {
            final text = notifier.isRecording ? 'Recording' : 'Not Recording';
            return Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(text),
                if (notifier.isRecording)
                  TextButton(
                    onPressed: () => notifier.stop(),
                    child: Text('stop'),
                  )
                else
                  TextButton(
                    onPressed: () => notifier.start(),
                    child: Text('Start'),
                  )
              ],
            );
          },
        ),
      ),
    ));
  }

  @override
  void dispose() {
    notifier.dispose();
    super.dispose();
  }
}

class PageNotifier extends ChangeNotifier {
  MediaRecorder? _mediaRecorder;
  bool get isRecording => _mediaRecorder != null;
  late final MediaStream _mediaStream;

  final constraints = {
    'audio': true,
    'video': true,
  };

  PageNotifier() {
    init();
  }
  Future<void> init() async {
    _mediaStream = await navigator.mediaDevices.getUserMedia(constraints);
  }

  void start() async {
    if (_mediaRecorder != null) return;
    try {
      _mediaRecorder = MediaRecorder();
      final dir = await getExternalStorageDirectory();
      await _mediaRecorder?.start(
        '${dir!.path}/recording.mp4',
        audioChannel: RecorderAudioChannel.INPUT,
        videoTrack: _mediaStream.getVideoTracks().first,
      );
    } catch (e, s) {
      _mediaRecorder?.stop();
      _mediaRecorder = null;
      print('Error while start recording');
      print(e);
      print(s);
    }
    notifyListeners();
  }

  void stop() async {
    await _mediaRecorder?.stop();
    _mediaRecorder = null;
    print('Recording done');
    notifyListeners();
  }

  @override
  void dispose() {
    _mediaStream.dispose();
    _mediaRecorder?.stop();
    _mediaRecorder = null;
    super.dispose();
  }
}
```

**Expected behavior**
App create file and record normally then doesn't crash when i stop recording.

**Platform information**

* **Flutter version**: 
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.3 22E252 darwin-arm, locale en-EG)
    • Flutter version 3.3.10 on channel stable at /Users/hosamhasan/fvm/versions/3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (8 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/hosamhasan/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/hosamhasan/Library/Android/sdk
    • Java binary at: /Users/hosamhasan/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment JBR-17.0.7+7-985.2-nomod (build 17.0.7+7-b985.2)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.2)
    • Android Studio at /Users/hosamhasan/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.3)
    • Android Studio at /Users/hosamhasan/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at /Users/hosamhasan/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.7571.182/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.1.3)
    • IntelliJ at /Users/hosamhasan/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.9161.38/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • Lenovo TB 8505FS (mobile) • HA16YBY9 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)           • macos    • darwin-arm64   • macOS 13.3 22E252 darwin-arm
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 115.0.5790.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
* **Plugin version**: 0.9.36
* **OS**: Android 
* **OS version**: 10
* **Device**:   Lenovo TB 8505FS (mobile) • HA16YBY9 • android-arm64  • Android 10 (API 29)

**Comment by dHanel** [comment]
same here. app crashes as soon as i execute mediaRecorder.start. testet on windows. is there any other way to record the stream?

**Comment by Hardik-Srivastava** [comment]
Did it got fixed @HosamHasanRamadan bro? I am too facing the same issue

**Comment by bantunes22** [comment]
Please check this PR:

https://github.com/flutter-webrtc/flutter-webrtc/pull/1810

**Comment by khlebobul** [comment]
I can reproduce a related failure with the current implementation in `flutter_webrtc 1.6.0`.

The app records a local `getUserMedia({audio: true, video: true})` stream on Android:

```dart
await recorder.start(
  path,
  videoTrack: stream.getVideoTracks().first,
  audioChannel: RecorderAudioChannel.INPUT,
);
```

The H.264 encoder initializes and reports its output format successfully:

```text
D/VideoFileRenderer: Encoder started successfully
D/VideoFileRenderer: EGL context created with shared context
E/VideoFileRenderer: encoder output format changed: {mime=video/avc, width=720, height=1280, ...}
```

However, there is no corresponding AAC/audio encoder initialization or output-format log. `VideoFileRenderer` waits for both video and audio tracks before calling `MediaMuxer.start()`, so the resulting MP4 remains `0 B` after `stop()`.

This happens in a standalone local-stream recording screen, without an active `RTCPeerConnection`. Is `RecorderAudioChannel.INPUT` expected to depend on the PeerConnection audio device module? If so, could the recorder consume the supplied local audio track directly, or fall back to a video-only muxer instead of producing an empty file?

Related iOS audio-recording issue: https://github.com/flutter-webrtc/flutter-webrtc/issues/2168
