### ISSUE TITLE
No implementation found for method listen on channel FlutterWebRTC.Method & FlutterWebRTC.Event

### ISSUE THREAD

**Issue by prabhuc94** [flutter-webrtc/flutter-webrtc#1424]
![image](https://github.com/flutter-webrtc/flutter-webrtc/assets/24710386/9aa7cd96-434e-4bab-8c11-5decec4e8bcd)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel FlutterWebRTC.Method)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      WebRTC.initialize (package:flutter_webrtc/src/native/utils.dart:39:7)
<asynchronous suspension>
#2      WebRTC.invokeMethod (package:flutter_webrtc/src/native/utils.dart:27:5)
<asynchronous suspension>
#3      RTCVideoRenderer.initialize (package:flutter_webrtc/src/native/rtc_video_renderer_impl.dart:23:22)
<asynchronous suspension>

flutter: PEER[ERROR]:	MissingPluginException(No implementation found for method initialize on channel FlutterWebRTC.Method)
flutter: DataTable2 built: 0ms

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel FlutterWebRTC.Event:
MissingPluginException(No implementation found for method listen on channel FlutterWebRTC.Event)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:652:9)
<asynchronous suspension>
====================================================================================================

**Comment by gisborne** [comment]
I also see this. Any solution?

**Comment by tigrenok00** [comment]
I have in on web, any news about it?
