### ISSUE TITLE
PlatformException(mediaStream AddTrack: Stream is null, null, null, null)

### ISSUE THREAD

**Issue by nguyenletrongnhanofficial** [flutter-webrtc/flutter-webrtc#1436]
When I call from 2 Android devices to each other, it works fine, but when I call from an iPhone device to an Android device, the error "PlatformException(mediaStream AddTrack: Stream is null, null, null, null)" appears. , can you help me? Thank you very much.

**Comment by hosein-nadali** [comment]
My problem too

**Comment by amatobi** [comment]
I have same issue, did you find a solution?

**Comment by sotrosh** [comment]
I have the same bug. How to fix it?

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(mediaStreamAddTrack: Stream is nil, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
message_codecs.dart:648
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
platform_channel.dart:334
<asynchronous suspension>
#2      MediaStreamNative.addTrack (package:flutter_webrtc/src/native/media_stream_impl.dart:61:7)
media_stream_impl.dart:61
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(mediaStreamAddTrack: Stream is nil, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
message_codecs.dart:648
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
platform_channel.dart:334
<asynchronous suspension>
#2      MediaStreamNative.addTrack (package:flutter_webrtc/src/native/media_stream_impl.dart:61:7)
media_stream_impl.dart:61
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(mediaStreamAddTrack: Stream is nil, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
message_codecs.dart:648
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
platform_channel.dart:334
<asynchronous suspension>
#2      MediaStreamNative.addTrack (package:flutter_webrtc/src/native/media_stream_impl.dart:61:7)
media_stream_impl.dart:61
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(mediaStreamAddTrack: Stream is nil, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
message_codecs.dart:648
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
platform_channel.dart:334
<asynchronous suspension>
#2      MediaStreamNative.addTrack (package:flutter_webrtc/src/native/media_stream_impl.dart:61:7)
media_stream_impl.dart:61
<asynchronous suspension>
```

**Comment by cloudwebrtc** [comment]
Under normal circumstances, all methods can be called correctly, but it is worth noting that when some exceptions in the native layer will cause such errors, please try to use Android Studio and observe the logcat log at runtime to see if there are other exception logs at the native level.
