### ISSUE TITLE
CameraAccessException. Camera unusable afterwards / crashes system

### ISSUE THREAD

**Issue by qqtb** [flutter-webrtc/flutter-webrtc#1528]
**Describe the bug**
 - Using the example app causes CameraAccessException when switching between cameras. 
This makes the camera unusable afterwards for the whole OS, or even crashes system so it reboots.
This happens after switching the camera a couple of times.

I'm trying to debug this but I'm new to Android. Will follow up with more information when available.

**To Reproduce**
- Open the example app
- Device Enumeration 
- Start a call by clicking the bottom right call icon 
- click the camera button and start switching cameras.

**Expected behavior**
- Switching cameras without crashing the whole system

**Platform information**

* **Flutter version**: 
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    • Flutter version 3.19.0 on channel stable at /Users/tmk/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (8 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

* **Plugin version**:
  - 0.9.48+hotfix.1

* **OS**: 
adb device:
    • SM G973F (mobile)           • RF8M6307SEM   • android-arm64  • Android 12 (API 31)

Logcat:
```

2024-02-22 07:40:36.694 10774-11090 MediaCodec              com...xample.flutter_webrtc_example  W  mapFormat: no mediaType information
2024-02-22 07:40:36.779 10774-11090 MediaCodec              com...xample.flutter_webrtc_example  W  mapFormat: no mediaType information
2024-02-22 07:40:36.818 10774-11090 MediaCodec              com...xample.flutter_webrtc_example  W  mapFormat: no mediaType information
2024-02-22 07:40:36.856 10774-11090 MediaCodec              com...xample.flutter_webrtc_example  W  mapFormat: no mediaType information
2024-02-22 07:40:37.117 10774-10774 ViewRootIm...nActivity] com...xample.flutter_webrtc_example  I  ViewPostIme pointer 0
2024-02-22 07:40:37.208 10774-10774 ViewRootIm...nActivity] com...xample.flutter_webrtc_example  I  ViewPostIme pointer 1
2024-02-22 07:40:37.300 10774-10932 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4002 ms. Frames received: 69. Dropped: 0. Rendered: 69. Render fps: 17,2. Average render time: 1654 us. Average swapBuffer time: 756 us.
2024-02-22 07:40:37.497 10774-11245 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraStatistics: Camera fps: 23.
2024-02-22 07:40:37.736 10774-10774 ViewRootIm...nActivity] com...xample.flutter_webrtc_example  I  ViewPostIme pointer 0
2024-02-22 07:40:37.827 10774-10774 ViewRootIm...nActivity] com...xample.flutter_webrtc_example  I  ViewPostIme pointer 1
2024-02-22 07:40:37.836 10774-10774 FlutterWebRTCPlugin     com...xample.flutter_webrtc_example  W  FlutterRTCVideoRenderer.setVideoTrack, set video track to null
2024-02-22 07:40:37.838 10774-11298 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraCapturer: Stop capture
2024-02-22 07:40:37.838 10774-11298 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraCapturer: Stop capture: Nulling session
2024-02-22 07:40:37.838 10774-11298 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraCapturer: Stop capture done
2024-02-22 07:40:37.838 10774-11298 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraCapturer: dispose
2024-02-22 07:40:37.838 10774-11298 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraCapturer: Stop capture
2024-02-22 07:40:37.838 10774-11245 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Stop camera2 session on camera 0
2024-02-22 07:40:37.838 10774-11298 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraCapturer: Stop capture: No session open
2024-02-22 07:40:37.838 10774-11298 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraCapturer: Stop capture done
2024-02-22 07:40:37.838 10774-11298 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  SurfaceTextureHelper: stopListening()
2024-02-22 07:40:37.839 10774-11245 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Stop internal
2024-02-22 07:40:37.839 10774-11245 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  SurfaceTextureHelper: stopListening()
2024-02-22 07:40:37.841 10774-10774 getUserMedia 3          com...xample.flutter_webrtc_example  W  getUserMedia 3
2024-02-22 07:40:37.842 10774-10774 getUserMedia 4          com...xample.flutter_webrtc_example  W  getUserMedia 4
2024-02-22 07:40:37.842 10774-10774 FlutterWebRTCPlugin     com...xample.flutter_webrtc_example  I  getUserMedia(video): ConstraintsMap{mMap={frameRate=30, width=1280, optional=[{sourceId=1}], height=720}}
2024-02-22 07:40:37.847 10774-10774 FlutterWebRTCPlugin     com...xample.flutter_webrtc_example  D  Creating video capturer using Camera2 API.
2024-02-22 07:40:37.847 10774-10774 FlutterWebRTCPlugin     com...xample.flutter_webrtc_example  D  create user specified camera 1 succeeded
2024-02-22 07:40:37.848 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglBase14Impl: Using OpenGL ES version 2
2024-02-22 07:40:37.849 10774-10774 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraCapturer: startCapture: 1280x720@30
2024-02-22 07:40:37.849 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Create new camera2 session on camera 1
2024-02-22 07:40:37.849 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: start
2024-02-22 07:40:37.852 10774-10774 FlutterWebRTCPlugin     com...xample.flutter_webrtc_example  D  changeCaptureFormat: 1280x720@30
2024-02-22 07:40:37.852 10774-10774 past permission         com...xample.flutter_webrtc_example  W  past permission
2024-02-22 07:40:37.853 10774-10774 past pushMap            com...xample.flutter_webrtc_example  W  past pushMap
2024-02-22 07:40:37.853 10774-10774 FlutterWebRTCPlugin     com...xample.flutter_webrtc_example  D  MediaStream id: a4c82292-e3b8-4ee1-800d-40b2644f0d18
2024-02-22 07:40:37.853 10774-10774 past putLocalStream     com...xample.flutter_webrtc_example  W  past putLocalStream
2024-02-22 07:40:37.853 10774-10774 past success            com...xample.flutter_webrtc_example  W  past success
2024-02-22 07:40:37.855 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Available preview sizes: [3840x2160, 3648x2736, 3648x2052, 3648x1728, 2736x2736, 2288x1080, 1920x1440, 1920x1080, 1920x912, 1440x1080, 1280x720, 1088x1088, 960x720, 720x480, 640x480, 640x360, 352x288, 320x240, 256x144, 176x144]
2024-02-22 07:40:37.855 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Available fps ranges: [[15.0:15.0], [15.0:20.0], [20.0:20.0], [24.0:24.0], [8.0:30.0], [10.0:30.0], [15.0:30.0], [30.0:30.0]]
2024-02-22 07:40:37.856 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Using capture format: 1280x720@[8.0:30.0]
2024-02-22 07:40:37.856 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Opening camera 1
2024-02-22 07:40:37.857 10774-11300 FlutterWebRTCPlugin     com...xample.flutter_webrtc_example  D  CameraEventsHandler.onCameraOpening: cameraName=1
2024-02-22 07:40:37.857 10774-10808 flutter                 com...xample.flutter_webrtc_example  I  track.settings {frameRate: 30, kind: videoinput, width: 1280, deviceId: 1, height: 720}
2024-02-22 07:40:37.857 10774-10808 flutter                 com...xample.flutter_webrtc_example  I  params degradationPreferenceRTCDegradationPreference.MAINTAIN_RESOLUTION
2024-02-22 07:40:37.858 10774-10774 FlutterWebRTCPlugin     com...xample.flutter_webrtc_example  W  FlutterRTCVideoRenderer.setVideoTrack, set video track to c77e362a-0300-4e66-a216-4ddaa3f9e335
2024-02-22 07:40:37.858 10774-10774 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Releasing.
2024-02-22 07:40:37.859 10774-11246 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  GlShader: Deleting shader.
2024-02-22 07:40:37.859 10774-11246 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: eglBase detach and release.
2024-02-22 07:40:37.860 10774-11246 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Quitting render thread.
2024-02-22 07:40:37.860 10774-10774 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Releasing done.
2024-02-22 07:40:37.860 10774-10774 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Initializing EglRenderer
2024-02-22 07:40:37.861 10774-11301 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: EglBase.create shared context
2024-02-22 07:40:37.862 10774-11301 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglBase14Impl: Using OpenGL ES version 2
2024-02-22 07:40:37.877 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Camera opened.
2024-02-22 07:40:37.878 10774-10789 CameraManagerGlobal     com...xample.flutter_webrtc_example  I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.cloudwebrtc.flutterflutterexample.flutter_webrtc_example API Level 2
2024-02-22 07:40:37.918 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Camera capture session configured.
2024-02-22 07:40:37.919 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Stabilization not available.
2024-02-22 07:40:37.919 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Using continuous video auto-focus.
2024-02-22 07:40:37.920 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Camera device successfully started.
2024-02-22 07:40:37.920 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraCapturer: Create session done. Switch state: IDLE
2024-02-22 07:40:37.920 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  SurfaceTextureHelper: Setting listener to org.webrtc.Camera2Session$CaptureSessionCallback$$ExternalSyntheticLambda0@db0a0a5
2024-02-22 07:40:37.923 10774-10789 CameraManagerGlobal     com...xample.flutter_webrtc_example  I  Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client com.cloudwebrtc.flutterflutterexample.flutter_webrtc_example API Level 2
2024-02-22 07:40:37.940 10774-10789 CameraManagerGlobal     com...xample.flutter_webrtc_example  I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.cloudwebrtc.flutterflutterexample.flutter_webrtc_example API Level 2
2024-02-22 07:40:37.997 10774-11245 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Stop done
2024-02-22 07:40:37.997 10774-11245 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Camera device closed.
2024-02-22 07:40:37.997 10774-11245 FlutterWebRTCPlugin     com...xample.flutter_webrtc_example  D  CameraEventsHandler.onFirstFrameAvailable
2024-02-22 07:40:37.997 10774-11298 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  SurfaceTextureHelper: dispose()
2024-02-22 07:40:37.999 10774-11330 CameraManagerGlobal     com...xample.flutter_webrtc_example  I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.cloudwebrtc.flutterflutterexample.flutter_webrtc_example API Level 2
2024-02-22 07:40:38.472 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Capture failed: android.hardware.camera2.CaptureFailure@9c4dc7a
2024-02-22 07:40:39.554 10774-11102 MediaCodec              com...xample.flutter_webrtc_example  I  setCodecState state(0), called in 6
2024-02-22 07:40:39.812 10774-11090 MediaCodec              com...xample.flutter_webrtc_example  I  setCodecState state(0), called in 6
2024-02-22 07:40:39.922 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  CameraStatistics: Camera fps: 0.
2024-02-22 07:40:41.284 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Capture failed: android.hardware.camera2.CaptureFailure@45b3c2b
2024-02-22 07:40:41.308 10774-10932 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4006 ms. Frames received: 16. Dropped: 0. Rendered: 16. Render fps: 4,0. Average render time: 1195 us. Average swapBuffer time: 527 us.
2024-02-22 07:40:41.556 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  E  Camera2Session: Error: Camera device has encountered a fatal error.
2024-02-22 07:40:41.557 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  Camera2Session: Stop internal
2024-02-22 07:40:41.557 10774-11300 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  SurfaceTextureHelper: stopListening()
2024-02-22 07:40:41.570 10774-11300 CameraCaptureSession    com...xample.flutter_webrtc_example  E  Session 0: Exception while stopping repeating: 
                                                                                                    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2378)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1305)
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
                                                                                                    	at org.webrtc.Camera2Session.stopInternal(Camera2Session.java:384)
                                                                                                    	at org.webrtc.Camera2Session.reportError(Camera2Session.java:405)
                                                                                                    	at org.webrtc.Camera2Session.-$$Nest$mreportError(Unknown Source:0)
                                                                                                    	at org.webrtc.Camera2Session$CameraStateCallback.onError(Camera2Session.java:110)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1776)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.$r8$lambda$KBQCqQRdhVVn7uHI9Xdha6OqnsU(Unknown Source:0)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl$$ExternalSyntheticLambda0.accept(Unknown Source:8)
                                                                                                    	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
                                                                                                    	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
                                                                                                    	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2024-02-22 07:40:41.872 10774-11301 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4008 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
2024-02-22 07:40:45.321 10774-10932 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4012 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
2024-02-22 07:40:45.879 10774-11301 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
2024-02-22 07:40:49.327 10774-10932 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
2024-02-22 07:40:49.890 10774-11301 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4010 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
2024-02-22 07:40:51.386 10774-10942 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  VolumeLogger: VOICE_CALL stream volume: 5 (max=8)
2024-02-22 07:40:53.339 10774-10932 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4011 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
2024-02-22 07:40:53.902 10774-11301 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4011 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
2024-02-22 07:40:57.347 10774-10932 org.webrtc.Logging      com...xample.flutter_webrtc_example  I  EglRenderer: Duration: 4008 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.

```

**Comment by ardeshir-33033** [comment]
Could you fix your issue?
