### ISSUE TITLE
video stops after playing sometime 

### ISSUE THREAD

**Issue by Hackerdash** [flutter-webrtc/flutter-webrtc#1537]
**Describe the bug**
the video stop after sometime and frozen at the frame
```
E/MethodChannel#FlutterWebRTC.Method(22466): Failed to handle method call
E/MethodChannel#FlutterWebRTC.Method(22466): java.lang.IllegalStateException: C++ addTransceiver failed.
E/MethodChannel#FlutterWebRTC.Method(22466): 	at org.webrtc.PeerConnection.addTransceiver(PeerConnection.java:1132)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at com.cloudwebrtc.webrtc.PeerConnectionObserver.addTransceiver(PeerConnectionObserver.java:935)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.addTransceiver(MethodCallHandlerImpl.java:1991)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:747)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#FlutterWebRTC.Method(22466): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/flutter (22466): Unable to RTCPeerConnection::addTransceiver: C++ addTransceiver failed.
I/flutter (22466): #0      Transport._produce (package:mediasoup_client_flutter/src/transport.dart:925:7)
I/flutter (22466): <asynchronous suspension>
I/flutter (22466): #1      FlexQueue._runTask (package:mediasoup_client_flutter/src/FlexQueue/flex_queue.dart:85:28)
I/flutter (22466): <asynchronous suspension>
I/brtctestexampl(22466): Background young concurrent copying GC freed 21659(937KB) AllocSpace objects, 0(0B) LOS objects, 28% free, 2536KB/3537KB, paused 11.415ms total 43.938ms
W/FlutterWebRTCPlugin(22466): FlutterRTCVideoRenderer.setVideoTrack, set video track to null
```
**To Reproduce**

**Expected behavior**
video need to play continually

**Platform information**
android

**Comment by sabreys** [comment]
Did you find any solution?
