### ISSUE TITLE
MediaStream.dispose() bug (mediastream not found on linux OS)

### ISSUE THREAD

**Issue by shivanshtalwar0** [flutter-webrtc/flutter-webrtc#1543]
**Describe the bug**
When calling `MediaStream.dispose()` library throw an exception that media stream is not found, this only happens on linux OS
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(MediaStreamDisposeFailed, stream [98C2C75D-0C4D-48F5-8387-67A667C09A62] not found!, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      MediaStreamNative.dispose (package:flutter_webrtc/src/native/media_stream_impl.dart:93:5)
<asynchronous suspension>
```

**To Reproduce**
simply run app on linux and call `MediaStream.dispose()`
**Expected behavior**
it should not throw an exception
**Platform information**
Linux

* **Flutter version**: 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on Linux Mint 20.3 5.16.12, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.87.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
* **Plugin version**:
0.9.48+hotfix.1
* **OS**: 
Desktop (Linux Mint)
* **OS version**:
Linux Mint 20.03 cinnamon

**Comment by shivanshtalwar0** [comment]
@cloudwebrtc  any update on this?

**Comment by dmitry-sinina** [comment]
I see same problem on Windows:
```
[2025-05-06 11:34:52.390] [Main] ERROR sip_service.dart:865 ::: SipService ::: stream cleanup failed: PlatformException(MediaStreamDisposeFailed, stream [4a7bcfcf-17a8-4d19-b455-db526229c193] not found!, null, null)
```
but only on Linux it causing application crash, so may be  it related to different exception handling.
