### ISSUE TITLE
MacOS/ios simulator/real ios: not getting srflx candidates

### ISSUE THREAD

**Issue by gisborne** [flutter-webrtc/flutter-webrtc#1613]
On a regular domestic router, no firewall, I'm unable to get any srflx candidates on either MacOS, iOS simulator iOS builds.

A browser test from the same machine works fine.

**To Reproduce**

Run the gist at: https://gist.github.com/gisborne/7a714c72444d91cbcd7f93a92aab73b3

**Expected behavior**

App should print 2 (ip4 and 6) srflx candidates

**Platform information**

M1 MacOS 14.5

* **Flutter version**: 

 % flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-AU)
    • Flutter version 3.22.2 on channel stable at /Users/gisborne/dev/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/gisborne/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/gisborne/Library/Android/sdk
    ✗ Android SDK file not found: /Users/gisborne/Library/Android/sdk/platforms/android-33/android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17890.8

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (6 available)
    • Iris (mobile)                       • 00008030-001879541480802E            • ios            • iOS 17.5.1 21F90
    • Athena (mobile)                     • 00008103-0008716C216B001E            • ios            • iOS 17.5.1 21F90
    • iPhone SE (3rd generation) (mobile) • 3492AACC-3C82-4924-B5B9-81656EE116A0 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 125.0.6422.61

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

* **Plugin version**:

dart_webrtc: 1.4.6+hotfix.1
flutter_webrtc: 0.11.1

* **OS**: 

Desktop/iOS simulator/iOS

* **OS version**:

Sonoma 14.5
iOS 17.5

**Comment by gisborne** [comment]
Likely related: I get a bunch of these reported to console:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
#0      ListBase.firstWhere (dart:collection/list.dart:132:5)
#1      _STUNTestState._processCandidate (package:dev/main.dart:100:24)
#2      _STUNTestState._createPeerConnection.<anonymous closure> (package:dev/main.dart:66:9)
#3      RTCPeerConnectionNative.eventListener (package:flutter_webrtc/src/native/rtc_peerconnection_impl.dart:162:25)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:541:14)
#7      _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
