### ISSUE TITLE
App crash in Android 14

### ISSUE THREAD

**Issue by harshmdr-devslane** [flutter-webrtc/flutter-webrtc#1631]
E/AndroidRuntime( 7187): java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION

I am using flutter_webrtc: 0.9.27.
 var stream = await navigator.mediaDevices.getDisplayMedia({
      'video': {'deviceId': 'broadcast'},
      'audio': false
    });

Any solution?

**Comment by Diya-Yi** [comment]
call this method Helper.requestCapturePermission() before navigator.mediaDevices.getDisplayMedia

**Comment by harshmdr-devslane** [comment]
Same issue 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to getDisplayMedia: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/flutter ( 5497): #0      MediaDeviceNative.getDisplayMedia (package:flutter_webrtc/src/native/mediadevices_impl.dart:68:7)
E/flutter ( 5497): <asynchronous suspension>
E/flutter ( 5497): #1      Signaling.shareScreen (package:pulse_screen_connect/signaling.dart:191:18)
E/flutter ( 5497): <asynchronous suspension>
E/flutter ( 5497): #2      _BroadcastState.onStart (package:pulse_screen_connect/widgets/pages/broadcast/broadcast.dart:103:7)
E/flutter ( 5497): <asynchronous suspension>
@Diya-Yi

**Comment by harshmdr-devslane** [comment]
Thank you @Diya-Yi

**Comment by harshmdr-devslane** [comment]
Not working after set targetSdversion to 34 

Failed to handle method call
E/MethodChannel#FlutterWebRTC.Method( 6423): java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Parcel.createException(Parcel.java:3041)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Parcel.readException(Parcel.java:3024)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Parcel.readException(Parcel.java:2966)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:313)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:84)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:75)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:236)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at com.cloudwebrtc.webrtc.OrientationAwareScreenCapturer.startCapture(OrientationAwareScreenCapturer.java:123)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.getDisplayMedia(GetUserMediaImpl.java:559)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.getDisplayMedia(GetUserMediaImpl.java:511)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.getDisplayMedia(MethodCallHandlerImpl.java:1404)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:634)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/MethodChannel#FlutterWebRTC.Method( 6423): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:940)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:192)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Binder.execTransactInternal(Binder.java:1339)
E/MethodChannel#FlutterWebRTC.Method( 6423): 	at android.os.Binder.execTransact(Binder.java:1275)
E/MethodChannel#FlutterWebRTC.Method( 6423):

**Comment by harshmdr-devslane** [comment]
When I do a fresh install and then Helper.requestCapturePermission() then gives error but after restart again then it works properly. Looks like android is not listening permission properly without hard reload.

**Comment by harshmdr-devslane** [comment]
@Diya-Yi can you please help here?

**Comment by harshmdr-devslane** [comment]
Also now it shows me 2 popups to start recording.

**Comment by lambiengcode** [comment]
hi @harshmdr-devslane,

Add this in your AndroidManifest.xml

```xml
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION"/>
```

Before call `getDisplayMedia`, add this:

```dart
final isGranted = await Helper.requestCapturePermission();

if (!isGranted) return;
```

**Comment by harshmdr-devslane** [comment]
I am using the same code and I have got isGranted is true after allow but `java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION` only first time and then after restart, it is working fine.

**Comment by harshmdr-devslane** [comment]
I am using android Emulator so may be the reason of it. I will try in real device and then let you know.
Thanks @lambiengcode

**Comment by harshmdr-devslane** [comment]
@lambiengcode Not working first time only.

**Comment by lambiengcode** [comment]
```dart
final isGranted = await Helper.requestCapturePermission();

if (!isGranted) return;

// start foreground service

var stream = await navigator.mediaDevices.getDisplayMedia({
```

Have you started the foreground service yet? @harshmdr-devslane

**Comment by harshmdr-devslane** [comment]
yes, i have stared foreground service using `flutter_background`

**Comment by harshmdr-devslane** [comment]
Is the sequence matters?
My sequence is 
1. `Start foreground service`  while app init.[One time]
2. Helper.requestCapturePermission() [while start broadcasting everytime]
3. navigator.mediaDevices.getDisplayMedia [Everytime]

**Comment by harshmdr-devslane** [comment]
I changed the sequence but still same result. Not working for first time.

**Comment by victortive** [comment]
This error is because Android 14 requires `android:foregroundServiceType` to be declared on the service tag in the android manifest file
```xml
<service
  android:name=".ForegroundService"
  android:stopWithTask="true"
  android:foregroundServiceType="phoneCall"
/>
```

**Comment by harshmdr-devslane** [comment]
Hi @victortive 
I am using the same code.
Only first time after install the app and after give permission, it give me the error and then after every time, it is working fine.

**Comment by EnterSoftwareSolutions** [comment]
Anyone who has found the solution?

**Comment by holzgeist** [comment]
Hi there,

I just solved a similar issue and stumbled over this issue

> Is the sequence matters? My sequence is
>     1. `Start foreground service`  while app init.[One time]
>     2. Helper.requestCapturePermission() [while start broadcasting everytime]
>     3. navigator.mediaDevices.getDisplayMedia [Everytime]

Yes, ordering matters, you need to first request capture permission, then start the foreground service (and then do whatever you do, getDisplayMedia in this case)

According to the [docs](https://developer.android.com/develop/background-work/services/foreground-services#fgs-prerequisites), the "standard" permission needs to be granted before attemping to use the foreground permission.

> For example, if you try to launch a foreground service of type location, the system checks to make sure your app already has either the ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission. If it doesn't, the system throws [SecurityException](https://developer.android.com/reference/java/lang/SecurityException).

**Comment by ardeshir-33033** [comment]
For any viewers, this is what you must do to share your screen on Android 14+.
1. Add package `flutter_background`
2. Add this in your AndroidManifest
  `    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION"/>`
3. Add this to your AndroidManifest
    `<service android:name="de.julianassmann.flutter_background.IsolateHolderService"
            android:foregroundServiceType="mediaProjection"
            android:enabled="true"
            android:exported="false"/>`
4. Call this function in main function of your app
   `Future<bool> startForegroundService() async {
  const androidConfig = FlutterBackgroundAndroidConfig(
    notificationTitle: 'Title of the notification',
    notificationText: 'Text of the notification',

  );
  await FlutterBackground.initialize(androidConfig: androidConfig);
  return true;
}`
5. Call This function to share the screen
   `  Future<void> screenSharing() async {
    FlutterBackground.enableBackgroundExecution();
    final isGranted = await Helper.requestCapturePermission();
    if (!isGranted) return;
    _shareStream = await navigator.mediaDevices.getDisplayMedia({
      'audio': true,
      'video': {
        'cursor': 'always',
      },
    });

    await _replaceStream(_shareStream!);
  }`

**Comment by Sam15b** [comment]
> For any viewers, this is what you must do to share your screen on Android 14+.
> 
> 1. Add package `flutter_background`
> 2. Add this in your AndroidManifest
> 
> ```
> <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
> 
>   <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
> 
>   <uses-permission android:name="android.permission.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION" />
> 
>   <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION"/>
> ```
> 
> 3. Add this to your AndroidManifest
>    `<service android:name="de.julianassmann.flutter_background.IsolateHolderService" android:foregroundServiceType="mediaProjection" android:enabled="true" android:exported="false"/>`
> 4. Call this function in main function of your app
> 
> ```
>  Future<bool> startForegroundService() async {
>  const androidConfig = FlutterBackgroundAndroidConfig(
>    notificationTitle: 'Title of the notification',
>    notificationText: 'Text of the notification',
> 
>  );
>  await FlutterBackground.initialize(androidConfig: androidConfig);
>  return true;
> }
> ```
> 
> 5. Call This function to share the screen
> 
> ```
>  Future<void> screenSharing() async {
>   FlutterBackground.enableBackgroundExecution();
>   final isGranted = await Helper.requestCapturePermission();
>   if (!isGranted) return;
>   _shareStream = await navigator.mediaDevices.getDisplayMedia({
>     'audio': true,
>     'video': {
>       'cursor': 'always',
>     },
>   });
> 
>   await _replaceStream(_shareStream!);
> }
> ```

But this is not working on Android 14 and 15 . it is Only working when you force your targetsdk to 28 . But this is not good when you publishing your App in google console. Becuz Google play console want taget sdk 33+

**Comment by Hamid313-coder** [comment]
For me, no need to user flutter_background package because it didn't work, I used method channel and added some native kotlin code for starting/stoping a forground service and then calling the getDisplayMedia. it wroked totally fine.
