### ISSUE TITLE
DTMF not working on Desktop apps

### ISSUE THREAD

**Issue by realdev-fr** [flutter-webrtc/flutter-webrtc#1711]
**Describe the bug**
When I try to send DTMF event, I got a Platform Exception error : 

`flutter: Dtmf tone => 1
flutter: [2024-11-23 18:11:43.733] Level.debug rtc_session.dart:860 ::: sendDTMF() | tones: 1
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(sendDtmf, sendDtmf() rtpSender is null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      RTCDTMFSenderNative.insertDTMF (package:flutter_webrtc/src/native/rtc_dtmf_sender_impl.dart:14:5)
<asynchronous suspension>`

However, it's working on Android.

Thanks for your help
**To Reproduce**
Tap 1 on keyboard
**Expected behavior**
The event triggered
**Platform information**
Windows 11, Ubuntu 22.04
* **Flutter version**: 3.24.4
* **Plugin version**: 0.12.1+hotfix.1

**Comment by ygor-dextak** [comment]
Same problem here, did you solve it?

**Comment by realdev-fr** [comment]
> Same problem here, did you solve it?

Yes ! 
Just change the DtmfMode to DtmfMode.INFO

`/// tones may be a single character or a string of dtmf digits
  void sendDTMF(dynamic tones, [Map<String, dynamic>? options]) {
    logger.d('sendDTMF() | tones: ${tones.toString()}');

    options = options ?? <String, dynamic>{};

    DtmfMode mode = DtmfMode.INFO;
....
`
And working :D

**Comment by ygor-dextak** [comment]
Thank you very much, it worked perfectly on a device that expects Dtmf mode INFO, I will test on other devices and adjust the library if necessary
