### ISSUE TITLE
No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals()

### ISSUE THREAD

**Issue by VNAPNIC** [flutter-webrtc/flutter-webrtc#189]
after run app on Emulator Nexus 7 API 29

```
2020-02-11 10:54:24.451 5469-5469/vn.gvntechnology.liveshop.dev E/org.webrtc.Logging: NativeLibrary: Failed to load native library: jingle_peerconnection_so
2020-02-11 10:54:24.452 5469-5469/vn.gvntechnology.liveshop.dev E/org.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/vn.gvntechnology.liveshop.dev-7q6JPLrZ4rp9oVTV-Rn5lA==/base.apk"],nativeLibraryDirectories=[/data/app/vn.gvntechnology.liveshop.dev-7q6JPLrZ4rp9oVTV-Rn5lA==/lib/x86, /data/app/vn.gvntechnology.liveshop.dev-7q6JPLrZ4rp9oVTV-Rn5lA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libjingle_peerconnection_so.so"
2020-02-11 10:54:24.456 5469-5469/vn.gvntechnology.liveshop.dev E/org.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/vn.gvntechnology.liveshop.dev-7q6JPLrZ4rp9oVTV-Rn5lA==/base.apk"],nativeLibraryDirectories=[/data/app/vn.gvntechnology.liveshop.dev-7q6JPLrZ4rp9oVTV-Rn5lA==/lib/x86, /data/app/vn.gvntechnology.liveshop.dev-7q6JPLrZ4rp9oVTV-Rn5lA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libjingle_peerconnection_so.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.webrtc.NativeLibrary$DefaultLoader.load(NativeLibrary.java:21)
        at org.webrtc.NativeLibrary.initialize(NativeLibrary.java:44)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:292)
        at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.<init>(FlutterWebRTCPlugin.java:103)
        at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.registerWith(FlutterWebRTCPlugin.java:88)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:20)
        at java.lang.reflect.Method.invoke(Native Method)
        at io.flutter.embedding.engine.FlutterEngine.registerPlugins(FlutterEngine.java:251)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:214)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:152)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:227)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:157)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:418)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-02-11 10:54:24.458 5469-5469/vn.gvntechnology.liveshop.dev E/gy.liveshop.de: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
```

```
java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
        at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:293)
        at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.<init>(FlutterWebRTCPlugin.java:103)
        at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.registerWith(FlutterWebRTCPlugin.java:88)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:20)
        at vn.gvntechnology.liveshop.MainActivity.configureFlutterEngine(MainActivity.kt:12)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:185)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:418)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by ycherniavskyi** [comment]
@VNAPNIC is this issue still exist?

**Comment by chertov** [comment]
I have the same problem
