### ISSUE TITLE
getUserMedia fails on Nokia 6.1

### ISSUE THREAD

**Issue by abergmeier** [flutter-webrtc/flutter-webrtc#217]
**Describe the bug**
When I try to use `getUserMedia` on _Nokia 6.1_, I get an exception:

```
I/FlutterWebRTCPlugin(14171): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
W/abergmeier.blau(14171): type=1400 audit(0.0:53219): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=13598 scontext=u:r:untrusted_app_27:s0:c0,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
I/FlutterWebRTCPlugin(14171): getUserMedia(video): com.cloudwebrtc.webrtc.utils.ConstraintsMap@7f7d488
E/libc    (14171): Access denied finding property "vendor.camera.aux.packagelist"
W/abergmeier.blau(14171): type=1400 audit(0.0:53220): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=13598 scontext=u:r:untrusted_app_27:s0:c0,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
D/FlutterWebRTCPlugin(14171): Creating video capturer using Camera2 API.
E/libc    (14171): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (14171): Access denied finding property "vendor.camera.aux.packagelist"
D/FlutterWebRTCPlugin(14171): Create front camera 1 succeeded
W/abergmeier.blau(14171): type=1400 audit(0.0:53221): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=13598 scontext=u:r:untrusted_app_27:s0:c0,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
I/org.webrtc.Logging(14171): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging(14171): CameraCapturer: startCapture: 320x240@15
I/org.webrtc.Logging(14171): Camera2Session: Create new camera2 session on camera 1
D/FlutterWebRTCPlugin(14171): changeCaptureFormat: 320x240@15
I/org.webrtc.Logging(14171): Camera2Session: start
D/FlutterWebRTCPlugin(14171): MediaStream id: df9e5fcb-7c05-41ff-8642-4b6315772afb
I/org.webrtc.Logging(14171): Camera2Session: Available preview sizes: [3264x2448, 3264x1836, 3264x1632, 3200x2400, 2592x1944, 2688x1512, 2448x2448, 2048x1536, 1944x1944, 1920x1080, 1600x1200, 1440x1080, 1280x960, 1280x720, 864x486, 864x480, 720x480, 640x480, 352x288, 320x240, 176x144, 144x176, 2304x1728]
I/org.webrtc.Logging(14171): Camera2Session: Available fps ranges: [[15.0:15.0], [20.0:20.0], [24.0:24.0], [7.0:30.0], [30.0:30.0]]
I/org.webrtc.Logging(14171): Camera2Session: Using capture format: 320x240@[15.0:15.0]
I/org.webrtc.Logging(14171): Camera2Session: Opening camera 1
D/FlutterWebRTCPlugin(14171): CameraEventsHandler.onCameraOpening: cameraName=1
W/main    (14171): type=1400 audit(0.0:53222): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=13598 scontext=u:r:untrusted_app_27:s0:c0,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
E/libc    (14171): Access denied finding property "persist.vendor.camera.privapp.list"
D/FlutterWebRTCPlugin(14171): addStreamcom.cloudwebrtc.webrtc.utils.AnyThreadResult@771e21
W/Binder:14171_3(14171): type=1400 audit(0.0:53223): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=13598 scontext=u:r:untrusted_app_27:s0:c0,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
E/libc    (14171): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraCaptureSession(14171): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(14171): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:464: Camera 1: Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession(14171): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:806)
E/CameraCaptureSession(14171): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession(14171): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1150)
E/CameraCaptureSession(14171): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:527)
E/CameraCaptureSession(14171): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:738)
E/CameraCaptureSession(14171): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:245)
E/CameraCaptureSession(14171): 	at android.os.Handler.handleCallback(Handler.java:883)
E/CameraCaptureSession(14171): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraCaptureSession(14171): 	at android.os.Looper.loop(Looper.java:214)
E/CameraCaptureSession(14171): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/CameraCaptureSession(14171): Caused by: android.os.ServiceSpecificException: cancelRequest:464: Camera 1: Error clearing streaming request: Function not implemented (-38) (code 10)
E/CameraCaptureSession(14171): 	at android.os.Parcel.createException(Parcel.java:2085)
E/CameraCaptureSession(14171): 	at android.os.Parcel.readException(Parcel.java:2039)
E/CameraCaptureSession(14171): 	at android.os.Parcel.readException(Parcel.java:1987)
E/CameraCaptureSession(14171): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:658)
E/CameraCaptureSession(14171): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
E/CameraCaptureSession(14171): 	... 8 more
```

**To Reproduce**

Code is:

```dart
  Future<MediaStream> createStream() async {
    final Map<String, dynamic> mediaConstraints = {
      'audio': true,
      'video': {
        'mandatory': {
          'minWidth':
              '320', // Provide your own width, height and frame rate here
          'minHeight': '240',
          'minFrameRate': '15',
        },
        'facingMode': 'user',
        'optional': [],
      }
    };

    return await navigator.getUserMedia(mediaConstraints);
  }
```

**Expected behavior**
Should return without an exception.

**Platform information**

* **Flutter version**:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /home/user/Software/flutter
    • Framework revision f139b11009 (5 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/user/Software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.6)
    • Android Studio at /home/user/Software/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Nokia 6 1 • PL2GAR98A2907007 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```
* **Plugin version**:
0.2.7
* **OS**: Android
* **OS version**: 10

**Comment by abergmeier** [comment]
So this seems to happen once I do a `getUserMedia` from two locations in the code. Is this currently not supported?

**Comment by cloudwebrtc** [comment]
It seems that the camera permission is not obtained

**Comment by FullstackJack** [comment]
Check camera permissions are set.

https://stackoverflow.com/questions/55990262/access-denied-for-property-vendor-camera-aux-packagelist

**Comment by abergmeier** [comment]
Sorry, I try to be more clear. It does work the first time I call `getUserMedia`. It fails the second time I call `getUserMedia` (with the previous stream still open).

**Comment by cloudwebrtc** [comment]
@abergmeier I guess it should be that `localStream.dispose()` is not executed correctly, causing the camera to not be released.
