### ISSUE TITLE
local stream freezes after sometime when the app is in background

### ISSUE THREAD

**Issue by AdiKK17** [flutter-webrtc/flutter-webrtc#276]
my local stream freezes after sometime when the app is in the background but the connection is maintained so no audio or video goes to the other person while I can see and hear the other person clearly.
I am using onePlus 6 and I am using ^0.2.6 version!

any solution to this?

**Comment by simon-twonary** [comment]
Did you add this permission to your AndroidManifest.xml file? 

```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

**Comment by AdiKK17** [comment]
Yes, I did.

**Comment by jcnoriega** [comment]
@AdiKK17 is the app in background or are you locking your phone?

**Comment by AdiKK17** [comment]
The issue occurs for both events

**Comment by pfaffenrodt** [comment]
It might be related.


Version: 0.2.8
Device: Sony Xperia 1 (Andorid 9)
Camera2 implementation.


crash occured while my app was in background.
```
E/org.webrtc.Logging(18785): Camera2Session: Error: Camera device could not be opened due to a device policy.
I/org.webrtc.Logging(18785): Camera2Session: Stop internal
I/org.webrtc.Logging(18785): SurfaceTextureHelper: stopListening()
E/CameraCaptureSession(18785): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(18785): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession(18785): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2563)
E/CameraCaptureSession(18785): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1140)
E/CameraCaptureSession(18785): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:527)
E/CameraCaptureSession(18785): 	at org.webrtc.Camera2Session.stopInternal(Camera2Session.java:380)
E/CameraCaptureSession(18785): 	at org.webrtc.Camera2Session.reportError(Camera2Session.java:401)
E/CameraCaptureSession(18785): 	at org.webrtc.Camera2Session.access$600(Camera2Session.java:35)
E/CameraCaptureSession(18785): 	at org.webrtc.Camera2Session$CameraStateCallback.onError(Camera2Session.java:114)
E/CameraCaptureSession(18785): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.notifyError(CameraDeviceImpl.java:2052)
E/CameraCaptureSession(18785): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.lambda$Sm85frAzwGZVMAK-NE_gwckYXVQ(Unknown Source:0)
E/CameraCaptureSession(18785): 	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$CameraDeviceCallbacks$Sm85frAzwGZVMAK-NE_gwckYXVQ.accept(Unknown Source:8)
E/CameraCaptureSession(18785): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:271)
E/CameraCaptureSession(18785): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
E/CameraCaptureSession(18785): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
E/CameraCaptureSession(18785): 	at android.os.Handler.handleCallback(Handler.java:883)
E/CameraCaptureSession(18785): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraCaptureSession(18785): 	at android.os.Looper.loop(Looper.java:359)
E/CameraCaptureSession(18785): 	at android.os.HandlerThread.run(HandlerThread.java:67)

```


Solution would be to start the camera inside an android foreground service. You would see an notification that indicate, that your app is doing something (capturing camera image).

Workaround would be to stop local stream, if app goes into background.

**Comment by AdiKK17** [comment]
@pfaffenrodt I get the same error. How to start the camera inside an android foreground service? Currently I'm using a workaround.

**Comment by jcnoriega** [comment]
@AdiKK17 android for security puropses shutsdown the camera and the microphone when the phone is locked. You have to put the code that uses the camera in a background service. I think that this should be included in the plugin. I had to fork the plugin and do a workaround myself for it.

**Comment by pfaffenrodt** [comment]
@jcnoriega you mean foreground service? background service would also shutdown the camera, I guess.

@AdiKK17 You have to fork and start camera from a Service like @jcnoriega have done it. 

Maybe someone create an pull request, with an optional start from an foreground service?

**Comment by carman247** [comment]
Any one have a definitely fix/correct way to handle this?

**Comment by pasle1109** [comment]
I have the same problem.

When entering the background on an Android device, only audio sound was output and the video stopped.

**Solution:**
My solution solved the issue by creating a stream when entering the foreground and replacing the created stream through the sender object in peerconnection.

```dart
void didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.resumed:
        if (WebRTC.platformIsAndroid) {
            MediaStream stream;
            RTCVideoRenderer renderer;
            RTCPeerConnection peerConnection;
          
            stream = await Helper.openCamera(mediaConstraints);
            stream.getVideoTracks()[0].enabled = true;
            renderer.srcObject = stream;
          
            await Future.forEach(stream.getTracks(), (track) async {
              final senders = await peerConnection.getSenders();
              senders.forEach((sender) async {
                sender.replaceTrack(track);
              });
            });
          }
        break;
      case AppLifecycleState.inactive:
        break;
      case AppLifecycleState.detached:
        break;
      case AppLifecycleState.paused:
        break;
    }
    super.didChangeAppLifecycleState(state);
} 
```
