### ISSUE TITLE
Could not find method android.hardware.camera2.CameraDevice.getId

### ISSUE THREAD

**Issue by bkhezry** [flutter-webrtc/flutter-webrtc#318]
**Describe the bug**
I use the last version of flutter-webrtc from the latest commit and when run sample demo application in debug mode, I got this huge errors:

```console
An Observatory debugger and profiler on GT I9301I is available at: http://127.0.0.1:40511/nbHgRJGedsE=/
I/org.webrtc.Logging(28437): NativeLibrary: Loading native library: jingle_peerconnection_so
I/org.webrtc.Logging(28437): NativeLibrary: Loading library: jingle_peerconnection_so
D/dalvikvm(28437): Trying to load lib /data/app-lib/com.github.bkhezry.webrtc-2/libjingle_peerconnection_so.so 0x421cf3a8
D/dalvikvm(28437): Added shared lib /data/app-lib/com.github.bkhezry.webrtc-2/libjingle_peerconnection_so.so 0x421cf3a8
I/org.webrtc.Logging(28437): PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
I/org.webrtc.Logging(28437): EglBase10Impl: Using OpenGL ES version 2
W/dalvikvm(28437): DexOpt: method is in an interface
I/dalvikvm(28437): Could not find method android.hardware.camera2.CameraDevice.getId, referenced from method com.cloudwebrtc.webrtc.GetUserMediaImpl.hasTorch
W/dalvikvm(28437): VFY: unable to resolve virtual method 882: Landroid/hardware/camera2/CameraDevice;.getId ()Ljava/lang/String;
W/dalvikvm(28437): VFY:  rejecting opcode 0x6e at 0x005a
W/dalvikvm(28437): VFY:  rejected Lcom/cloudwebrtc/webrtc/GetUserMediaImpl;.hasTorch (Ljava/lang/String;Lio/flutter/plugin/common/MethodChannel$Result;)V
W/dalvikvm(28437): Verifier rejected class Lcom/cloudwebrtc/webrtc/GetUserMediaImpl;
E/flutter (28437): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.VerifyError: com/cloudwebrtc/webrtc/GetUserMediaImpl
E/flutter (28437): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.ensureInitialized(MethodCallHandlerImpl.java:135)
E/flutter (28437): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:155)
E/flutter (28437): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/flutter (28437): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (28437): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (28437): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (28437): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter (28437): 	at android.os.Looper.loop(Looper.java:123)
E/flutter (28437): 	at android.app.ActivityThread.main(ActivityThread.java:5476)
E/flutter (28437): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter (28437): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter (28437): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/flutter (28437): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/flutter (28437): 	at dalvik.system.NativeStart.main(Native Method)
E/flutter (28437): 
F/flutter (28437): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
F/libc    (28437): Fatal signal 6 (SIGABRT) at 0x00006f15 (code=-6), thread 28437 (.bkhezry.webrtc)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/s3ve3gxx/s3ve3g:4.4.2/KOT49H/I9301IXXUAPG3:user/release-keys'
Revision: '4'
pid: 28437, tid: 28437, name: .bkhezry.webrtc  >>> com.github.bkhezry.webrtc <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    r0 00000000  r1 00006f15  r2 00000006  r3 00000000
    r4 00000006  r5 00000016  r6 00006f15  r7 0000010c
    r8 bea95004  r9 7ebf0f98  sl 401b0b43  fp 401b0a4c
    ip 416f9241  sp bea94f78  lr 40126205  pc 40135164  cpsr 000b0010
    d0  0000000000000000  d1  0000000000000000
    d2  0000000000000000  d3  0000000000000000
    d4  646f6874654d6e6f  d5  74654d286c6c6143
    d6  486c6c6143646f68  d7  6d4972656c646e61
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 6378456b63656843  d17 65286e6f69747065
    d18 64696f72646e612e  d19 616e7265746e692e
    d20 67795a2e736f2e6c  d21 2e74696e4965746f
    d22 67795a286e69616d  d23 2e74696e4965746f
    d24 3fc74721cad6b0ed  d25 3fc2f112df3e5244
    d26 40026bb1bbb55516  d27 0000000000000000
    d28 0000000000000000  d29 0000000000000000
    d30 0000000000000000  d31 0000000000000000
    scr 60000012
backtrace:
    #00  pc 00022164  /system/lib/libc.so (tgkill+12)
    #01  pc 00013201  /system/lib/libc.so (pthread_kill+48)
    #02  pc 00013415  /system/lib/libc.so (raise+10)
    #03  pc 000120e3  /system/lib/libc.so
    #04  pc 00021a18  /system/lib/libc.so (abort+4)
    #05  pc 00011f27  /data/app-lib/com.github.bkhezry.webrtc-2/libflutter.so
stack:
         bea94f38  bea9503c  [stack]
         bea94f3c  00000020  
         bea94f40  be323439  
         bea94f44  00000000  
         bea94f48  bea9503c  [stack]
         bea94f4c  7911b749  /data/app-lib/com.github.bkhezry.webrtc-2/libflutter.so
         bea94f50  000003ae  
         bea94f54  7911b731  /data/app-lib/com.github.bkhezry.webrtc-2/libflutter.so
         bea94f58  00000080  
         bea94f5c  79c1d50a  
         bea94f60  4017b409  /system/lib/liblog.so
         bea94f64  7811f43e  /data/app-lib/com.github.bkhezry.webrtc-2/libflutter.so
         bea94f68  7f1ebec8  
         bea94f6c  00000000  
         bea94f70  4015d1d8  /system/lib/libc.so
         bea94f74  77410308  
    #00  bea94f78  00000006  
         bea94f7c  00000016  
         bea94f80  00006f15  
         bea94f84  416f9241  /system/lib/libdvm.so
         bea94f88  416f9241  /system/lib/libdvm.so
         bea94f8c  40126205  /system/lib/libc.so (pthread_kill+52)
    #01  bea94f90  00000006  
         bea94f94  00000000  
         bea94f98  00000003  
         bea94f9c  40126419  /system/lib/libc.so (raise+14)
    #02  bea94fa0  bea94fac  [stack]
         bea94fa4  401250e7  /system/lib/libc.so
memory near r1:
    00006ef4 ffffffff ffffffff ffffffff ffffffff  
    00006f04 ffffffff ffffffff ffffffff ffffffff  
    00006f14 ffffffff ffffffff ffffffff ffffffff  
    00006f24 ffffffff ffffffff ffffffff ffffffff  
    00006f34 ffffffff ffffffff ffffffff ffffffff  
    00006f44 ffffffff ffffffff ffffffff ffffffff  
    00006f54 ffffffff ffffffff ffffffff ffffffff  
    00006f64 ffffffff ffffffff ffffffff ffffffff  
    00006f74 ffffffff ffffffff ffffffff ffffffff  
    00006f84 ffffffff ffffffff ffffffff ffffffff  
    00006f94 ffffffff ffffffff ffffffff ffffffff  
    00006fa4 ffffffff ffffffff ffffffff ffffffff  
    00006fb4 ffffffff ffffffff ffffffff ffffffff  
    00006fc4 ffffffff ffffffff ffffffff ffffffff  
    00006fd4 ffffffff ffffffff ffffffff ffffffff  
    00006fe4 ffffffff ffffffff ffffffff ffffffff  
memory near r6:
    00006ef4 ffffffff ffffffff ffffffff ffffffff  
    00006f04 ffffffff ffffffff ffffffff ffffffff  
    00006f14 ffffffff ffffffff ffffffff ffffffff  
    00006f24 ffffffff ffffffff ffffffff ffffffff  
    00006f34 ffffffff ffffffff ffffffff ffffffff  
    00006f44 ffffffff ffffffff ffffffff ffffffff  
    00006f54 ffffffff ffffffff ffffffff ffffffff  
    00006f64 ffffffff ffffffff ffffffff ffffffff  
    00006f74 ffffffff ffffffff ffffffff ffffffff  
    00006f84 ffffffff ffffffff ffffffff ffffffff  
    00006f94 ffffffff ffffffff ffffffff ffffffff  
    00006fa4 ffffffff ffffffff ffffffff ffffffff  
    00006fb4 ffffffff ffffffff ffffffff ffffffff  
    00006fc4 ffffffff ffffffff ffffffff ffffffff  
    00006fd4 ffffffff ffffffff ffffffff ffffffff  
    00006fe4 ffffffff ffffffff ffffffff ffffffff  
memory near r8:
    bea94fe4 7f1ebec8 416b55a8 00000002 bea950c4  
    bea94ff4 7902d11d 7815768d 00000002 00000010  
    bea95004 795529b0 79552068 7967e400 00000000  
    bea95014 00000000 00000000 79c1d498 79c1d50a  
    bea95024 79c1d517 00000081 0000007f 79c1d498  
    bea95034 79c1d50a 00000010 795529c4 00001002  
    bea95044 00000006 00000000 00000000 00000000  
    bea95054 bea95008 7967e400 00000000 00000000  
    bea95064 00000000 00000000 00000000 00000000  
    bea95074 00000000 00000000 00000000 00000000  
    bea95084 00000000 00000020 00000003 7813901f  
    bea95094 000003ae b7b00021 416b55a8 b7f0001d  
    bea950a4 416b55a8 bea950e4 bea950c4 00000000  
    bea950b4 00000037 bea950fc 7902a4cf 79c1bf98  
    bea950c4 7eca96e8 7ebf0ee0 00000002 bea950e4  
    bea950d4 7ebf0fa4 00000037 79065911 00000001  
memory near r9:
    7ebf0f78 00000018 00000023 795704f8 81b543f1  
    7ebf0f88 795749c4 81d56901 7ebf0fa0 81d56989  
    7ebf0f98 7957452c 00000023 79555098 79551e10  
    7ebf0fa8 79c1bf98 79c19798 79573688 7eca96e8  
    7ebf0fb8 7957452c 0000001b 00000000 00000002  
    7ebf0fc8 00000002 7ebf0ee0 795771f0 0000008b  
    7ebf0fd8 7ebef9b8 40161240 69746365 61466e6f  
    7ebf0fe8 726f7463 50203a79 43726565 656e6e6f  
    7ebf0ff8 6f697463 6361466e 79726f74 73617720  
    7ebf1008 696e6920 6c616974 64657a69 74697720  
    7ebf1018 74756f68 206e6120 656a6e69 64657463  
    7ebf1028 676f4c20 6c626167 41202e65 6520796e  
    7ebf1038 74736978 20676e69 67676f4c 656c6261  
    7ebf1048 6c697720 6562206c 6c656420 64657465  
    7ebf1058 00000088 00000013 00000000 00000000  
    7ebf1068 00000010 000000b3 7ebf1080 0000002c  
memory near sl:
    401b0b20 206c6c6f 6e657665 30207374 20782578  
    401b0b30 77206e6f 20656b61 64616572 70697020  
    401b0b40 49002e65 726f6e67 20676e69 78656e75  
    401b0b50 74636570 65206465 6c6c6f70 65766520  
    401b0b60 2073746e 78257830 206e6f20 25206466  
    401b0b70 68742064 69207461 6f6e2073 6e6f6c20  
    401b0b80 20726567 69676572 72657473 002e6465  
    401b0b90 6c756f43 6f6e2064 72632074 65746165  
    401b0ba0 6b617720 69702065 202e6570 72726520  
    401b0bb0 253d6f6e 6f430064 20646c75 20746f6e  
    401b0bc0 656b616d 6b617720 65722065 70206461  
    401b0bd0 20657069 2d6e6f6e 636f6c62 676e696b  
    401b0be0 6520202e 6f6e7272 0064253d 6c756f43  
    401b0bf0 6f6e2064 616d2074 7720656b 20656b61  
    401b0c00 74697277 69702065 6e206570 622d6e6f  
    401b0c10 6b636f6c 2e676e69 72652020 3d6f6e72  
memory near fp:
    401b0a2c 202c657a 756f436d 202c746e 756f6d61  
    401b0a3c 0029746e 75736572 2120746c 0030203d  
    401b0a4c 706f6f4c 43007265 646c756f 746f6e20  
    401b0a5c 6c6c6120 7461636f 4c542065 656b2053  
    401b0a6c 70002e79 65726874 6f5f6461 2065636e  
    401b0a7c 6c696166 57006465 756f4300 6e20646c  
    401b0a8c 7720746f 65746972 6b617720 69732065  
    401b0a9c 6c616e67 7265202c 3d6f6e72 45006425  
    401b0aac 726f7272 6d657220 6e69766f 70652067  
    401b0abc 206c6c6f 6e657665 66207374 6620726f  
    401b0acc 64252064 7265202c 3d6f6e72 50006425  
    401b0adc 206c6c6f 6c696166 77206465 20687469  
    401b0aec 75206e61 7078656e 65746365 72652064  
    401b0afc 2c726f72 72726520 253d6f6e 67490064  
    401b0b0c 69726f6e 7520676e 7078656e 65746365  
    401b0b1c 70652064 206c6c6f 6e657665 30207374  
memory near ip:
    416f9220 4a0647e0 4629a805 f7fe447a b00afe4b  
    416f9230 87f0e8bd 00082dc5 0006aa3e 0006a9be  
    416f9240 47f0e92d 4b1a461e 2500b08a 447b4604  
    416f9250 f8dd4688 46299048 1d989005 a8059006  
    416f9260 f04f4617 95070a01 a020f88d f958f7fe  
    416f9270 a8054a10 46234651 8000f8cd 9701447a  
    416f9280 f8cd9602 f7fe900c 6861fe1d 9000f8cd  
    416f9290 463a4620 f8d14633 4641c340 4a0647e0  
    416f92a0 4629a805 f7fe447a b00afe0d 87f0e8bd  
    416f92b0 00081d14 0006a9c2 0006a942 47f0e92d  
    416f92c0 4b1a461e 2500b08a 447b4604 f8dd4688  
    416f92d0 46299048 1d989005 a8059006 f04f4617  
    416f92e0 95070a01 a020f88d f91af7fe a8054a10  
    416f92f0 46234651 8000f8cd 9701447a f8cd9602  
    416f9300 f7fe900c 6861fddf 9000f8cd 463a4620  
    416f9310 f8d14633 4641c33c 4a0647e0 4629a805  
memory near sp:
    bea94f58 00000080 79c1d50a 4017b409 7811f43e  
    bea94f68 7f1ebec8 00000000 4015d1d8 77410308  
    bea94f78 00000006 00000016 00006f15 416f9241  
    bea94f88 416f9241 40126205 00000006 00000000  
    bea94f98 00000003 40126419 bea94fac 401250e7  
    bea94fa8 bea95004 ffffffdf 4015d000 bea94fdc  
    bea94fb8 bea94fdc bea94fdc 00000003 bea95004  
    bea94fc8 bea94fdc 40134a1c 4017b409 79037f2b  
    bea94fd8 bea95004 00000081 00000072 7f1ebec8  
    bea94fe8 416b55a8 00000002 bea950c4 7902d11d  
    bea94ff8 7815768d 00000002 00000010 795529b0  
    bea95008 79552068 7967e400 00000000 00000000  
    bea95018 00000000 79c1d498 79c1d50a 79c1d517  
    bea95028 00000081 0000007f 79c1d498 79c1d50a  
    bea95038 00000010 795529c4 00001002 00000006  
    bea95048 00000000 00000000 00000000 bea95008  
code around pc:
    40135144 e8bd00f0 e3700a01 912fff1e e2600000  
    40135154 ea006e48 e92d50f0 e3a07f43 ef000000  
    40135164 e8bd50f0 e3700a01 912fff1e e2600000  
    40135174 ea006e40 e92d50f0 e3a070ee ef000000  
    40135184 e8bd50f0 e3700a01 912fff1e e2600000  
    40135194 ea006e38 f200429a bf0080b9 f040f891  
    401351a4 4001e92d f2c02a04 2a1080a5 8093f2c0  
    401351b4 f2c02a20 2a408088 ea4fdb7f f1bc1c92  
    401351c4 dd6c0f0a 0600e92d 0f40f1bc f500dd4a  
    401351d4 f5016e80 ebae7920 ea4f0e09 ea4f5e4e  
    401351e4 f50e5e5e ebbc7e20 dd3b1f9e f04fbfc4  
    401351f4 ebd9090a dd35199e 0a0eeb01 0a3ff02a  
    40135204 1c9eebac bfd245e1 0c09ebac f04f46e1  
    40135214 f8910c00 f891f240 f921f280 f921028d  
    40135224 f8da428d f1b93000 f9000901 f900028d  
    40135234 f10a428d d1ee0a40 0f00f1bc f5bcd02b  
code around lr:
    401261e4 447b4b13 42b3e010 6a1ed10e 44784811  
    401261f4 ec50f7fb e9e8f00d 46224631 efaaf00e  
    40126204 d00a3001 e00b2400 2b00681b 480ad1eb  
    40126214 44782403 ec3ef7fb f001e002 6804f9ff  
    40126224 f9fcf001 46206005 bf00bd70 0003b1d2  
    40126234 0003b1c6 0003b1be 0003b19a bf7ef7ff  
    40126244 4a3e4b3d e92d447b b08b43f0 4606589c  
    40126254 6823460d 930946a1 f9e0f001 8000f8d0  
    40126264 d0482d00 f0104628 280ff8f7 d8444604  
    40126274 ffe4f7ff d1064286 4629200f e8b2f00d  
    40126284 d03c2800 482ee02e f7fb4478 482deb82  
    40126294 e0154478 d11342b0 482b6a06 f7fb4478  
    401262a4 4a2aebfa 46332120 a801447a f96ef013  
    401262b4 a8012101 fc8cf01a 46061c42 e011d104  
    401262c4 28006800 e02cd1e6 46294630 f00d4622  
    401262d4 1c43e8ee d11e4607 f9a0f001 29046801  
```
I just add Proguard rules to the app and it not fix this error. It works fine with Android 10
#205

**To Reproduce**
use the latest version of plugin #316 and run demo application(flutter-webrtc-demo ) on the android device with android 4.4.2.

**Platform information**

* **Flutter version**:

```console
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at /home/bkhezry/flutter
    • Framework revision bbfbf1770c (13 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/bkhezry/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/bkhezry/Android/Sdk
    • Java binary at: /home/bkhezry/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/bkhezry/android-studio
    • Flutter plugin version 49.0.2-dev.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Redmi Note 7 (mobile) • 1762cc53 • android-arm64 • Android 10 (API 29)
    • GT I9301I (mobile)    • 64259743 • android-arm   • Android 4.4.2 (API 19)

• No issues found!

```

* **Plugin version**: latest version
* **OS**: Android
* **OS version**: 4.4.2

**Comment by carloselborges** [comment]
Same here @bkhezry.
Android 4.4.2 Samsung S4 Mini

### android/app/build.gradle
```gradle
// ...
android {
    compileSdkVersion 29
    // ...
    defaultConfig {
        // ...
        consumerProguardFiles 'proguard-rules.pro'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug

            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
// ...
```

### android/app/proguard-rules.pro
```proguard
# Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

# Flutter WebRTC
-keep class com.cloudwebrtc.webrtc.** {*;}
-keep class org.webrtc.** {*;}
```



### Error log
The error is happening when **running** the app. It **compiles ok**.
```
[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(44)] java.lang.VerifyError: com/cloudwebrtc/webrtc/GetUserMediaImpl
        at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.ensureInitialized(:141)
        at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(:161)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:692)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:131)
        at android.app.ActivityThread.main(ActivityThread.java:5593)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(943)] Check failed: CheckException(env). 
```

**Comment by IvanSyabro** [comment]
I'm experiencing the same issue, device: Acer z500 4.4
