### ISSUE TITLE
first few calls unsuccessful

### ISSUE THREAD

**Issue by min-wai** [flutter-webrtc/flutter-webrtc#374]
**Describe the bug**
Error while creating AudioRecord object even though I didn't implement audio recording.

```
E/IAudioFlinger(27812): createRecord returned error -22
E/AudioRecord(27812): createRecord_l(1769108859): AudioFlinger could not create record track, status: -22
E/AudioRecord-JNI(27812): Error creating AudioRecord instance: initialization check failed with status -22.
E/android.media.AudioRecord(27812): Error code -20 when initializing native AudioRecord object.
E/org.webrtc.Logging(27812): WebRtcAudioRecordExternal: Init recording error: Cannot create AudioRecord
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal: Android SDK: 29, Release: 10, Brand: Xiaomi, Device: platina, Id: QKQ1.190910.002, Hardware: qcom, Manufacturer: Xiaomi, Model: MI 8 Lite, Product: platina
I/AudioManager(27812): In isSpeakerphoneOn(), calling application: com.nwt.myhealthcarefordoctors
I/AudioManager(27812): In isBluetoothScoOn(), calling application: com.nwt.myhealthcarefordoctors
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal: Audio State: audio mode: MODE_IN_COMMUNICATION, has mic: true, mic muted: false, music active: false, speakerphone: true, BT SCO: false
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal: Audio State: 
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   fixed volume=false
D/AudioManager(27812): getStreamVolume isRestricted mode = 0
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   STREAM_VOICE_CALL: volume=11, max=11, muted=false
D/AudioManager(27812): getStreamVolume isRestricted mode = 0
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   STREAM_MUSIC: volume=11, max=15, muted=false
D/AudioManager(27812): getStreamVolume isRestricted mode = 0
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   STREAM_RING: volume=5, max=15, muted=false
D/AudioManager(27812): getStreamVolume isRestricted mode = 0
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   STREAM_ALARM: volume=15, max=15, muted=false
D/AudioManager(27812): getStreamVolume isRestricted mode = 0
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   STREAM_NOTIFICATION: volume=5, max=15, muted=false
D/AudioManager(27812): getStreamVolume isRestricted mode = 0
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   STREAM_SYSTEM: volume=5, max=15, muted=false
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal: Audio Devices: 
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   TYPE_BUILTIN_EARPIECE(out): channels=[1], encodings=[2], sample rates=[48000], id=2
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   TYPE_BUILTIN_SPEAKER(out): channels=[2], encodings=[2], sample rates=[48000], id=3
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   TYPE_TELEPHONY(out): channels=[1, 2], encodings=[2], sample rates=[8000, 16000], id=8
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   TYPE_BUILTIN_MIC(in): channels=[1, 2], encodings=[2], sample rates=[8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000], id=15
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   TYPE_TELEPHONY(in): channels=[1, 2], encodings=[2], sample rates=[8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000], id=11
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   TYPE_BUILTIN_MIC(in): channels=[1, 2], encodings=[2], sample rates=[8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000], id=16
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal:   TYPE_FM_TUNER(in): channels=[1, 2], encodings=[2], sample rates=[8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000], id=12
I/org.webrtc.Logging(27812): WebRtcAudioRecordExternal: Number of active recording sessions: 1
W/System.err(27812): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.AudioRecord.getAudioSessionId()' on a null object reference
W/System.err(27812):    at org.webrtc.audio.WebRtcAudioRecord.logRecordingConfigurations(WebRtcAudioRecord.java:435)
W/System.err(27812):    at org.webrtc.audio.WebRtcAudioRecord.reportWebRtcAudioRecordInitError(WebRtcAudioRecord.java:484)
W/System.err(27812):    at org.webrtc.audio.WebRtcAudioRecord.initRecording(WebRtcAudioRecord.java:307)
E/rtc     (27812): 
E/rtc     (27812): 
E/rtc     (27812): #
E/rtc     (27812): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../../../usr/local/google/home/sakal/code/webrtc-aar-release/src/sdk/android/src/jni/jni_generator_helper.h, line 94
E/rtc     (27812): # last system error: 0
E/rtc     (27812): # Check failed: !env->ExceptionCheck()
E/rtc     (27812): # 
F/libc    (27812): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 28112 (worker_thread -), pid 27812 (hcarefordoctors)
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

**Comment by min-wai** [comment]
Update: the error has disappeared, but sometimes, video/voice call fails. 

```
I/flutter ( 6228): ICE connection state changed: RTCIceConnectionState.RTCIceConnectionStateChecking
I/flutter ( 6228): ICE connection state changed: RTCIceConnectionState.RTCIceConnectionStateFailed
```

When I checked Coturn log, I found out refresh allocation with lifetime 0 was being sent immediately after candidate allocation. I have no idea why it happens and only happens sometimes.

**Comment by cloudwebrtc** [comment]
The current MediaRecorder function is unstable

**Comment by min-wai** [comment]
> The current MediaRecorder function is unstable

Media Recorder issue has disappeared. 
Issue is client is sending lifetime 0 at the start of some calls, making the connection drop suddenly.

```
Oct 26 07:27:01 myhealthcare turnserver: 2983: session 000000000000000039: delete: realm=<newwave-tech.net>, username=<turnadmin>
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: peer 10.179.47.223 lifetime updated: 300
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: realm <newwave-tech.net> user <turnadmin>: incoming packet CREATE_PERMISSION processed, success
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: peer 128.199.215.42 lifetime updated: 300
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: realm <newwave-tech.net> user <turnadmin>: incoming packet CREATE_PERMISSION processed, success
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: peer 37.111.0.2 lifetime updated: 300
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: realm <newwave-tech.net> user <turnadmin>: incoming packet CREATE_PERMISSION processed, success
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: realm <newwave-tech.net> user <turnadmin>: incoming packet CREATE_PERMISSION processed, error 403: Forbidden IP
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: realm <newwave-tech.net> user <turnadmin>: incoming packet message processed, error 403: Forbidden IP
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: refreshed, realm=<newwave-tech.net>, username=<turnadmin>, lifetime=0
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000040: realm <newwave-tech.net> user <turnadmin>: incoming packet REFRESH processed, success
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000025: realm <newwave-tech.net> user <turnadmin>: incoming packet CREATE_PERMISSION processed, error 403: Forbidden IP
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000025: realm <newwave-tech.net> user <turnadmin>: incoming packet message processed, error 403: Forbidden IP
Oct 26 07:27:02 myhealthcare turnserver: 2983: session 000000000000000025: peer 103.217.156.204 lifetime updated: 300

```
