### ISSUE TITLE
Screen sharing not works in Android 10

### ISSUE THREAD

**Issue by pravinkumarputta** [flutter-webrtc/flutter-webrtc#377]
Showing below error:

```
E/AndroidRuntime( 5480): java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 5480): 	at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime( 5480): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime( 5480): 	at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime( 5480): 	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime( 5480): 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
E/AndroidRuntime( 5480): 	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
E/AndroidRuntime( 5480): 	at org.webrtc.ScreenCapturerAndroid.startCapture(ScreenCapturerAndroid.java:114)
E/AndroidRuntime( 5480): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl$3.onReceiveResult(GetUserMediaImpl.java:498)
E/AndroidRuntime( 5480): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime( 5480): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 5480): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 5480): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 5480): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 5480): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5480): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 5480): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 5480): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 5480): 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:476)
E/AndroidRuntime( 5480): 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E/AndroidRuntime( 5480): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
E/AndroidRuntime( 5480): 	at android.os.Binder.execTransact(Binder.java:994)
E/AndroidRuntime( 5480): 
I/Process ( 5480): Sending signal. PID: 5480 SIG: 9
Lost connection to device.
```

Is there any foreground service available in this library? So I can make its entry to my AndroidManifest.xml file.

**Comment by pravinkumarputta** [comment]
By adding foreground service using ```flutter_foreground_plugin``` it worked.

Steps to resolve:
1. add ```flutter_foreground_plugin``` to your project.
2. add below permission to the AndroidManifest.xml file.
```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```
3. add below service to the AndroidManifest.xml file.
```
<service android:name="changjoopark.com.flutter_foreground_plugin.FlutterForegroundService"
            android:foregroundServiceType="mediaProjection"
            tools:targetApi="q"
            android:enabled="true"
            android:exported="false"/>
```
4. add below methods to your flutter code.
```
  startForegroundService() async {
    await FlutterForegroundPlugin.setServiceMethodInterval(seconds: 5);
    await FlutterForegroundPlugin.setServiceMethod(globalForegroundService);
    await FlutterForegroundPlugin.startForegroundService(
      holdWakeLock: false,
      onStarted: () {
        print("Foreground on Started");
      },
      onStopped: () {
        print("Foreground on Stopped");
      },
      title: "Tcamera",
      content: "Tcamera sharing your screen.",
      iconName: "ic_stat_mobile_screen_share",
    );
    return true;
  }

  static void globalForegroundService() {
    debugPrint("current datetime is ${DateTime.now()}");
  }
```
5. Finally call ```startForegroundService()``` method before calling ```MediaDevices.getDisplayMedia(mediaConstraints)```.

That's it. Happy coding...

**Comment by samuelg123** [comment]
Thank you very much. It worked! 

I think this bug needs to be fixed inside flutter-webrtc.

**Comment by sawproduction** [comment]
Not working for me
