### ISSUE TITLE
Can't initialize media recorder

### ISSUE THREAD

**Issue by ali-heidari** [flutter-webrtc/flutter-webrtc#391]
**Describe the bug**

I am trying to record my local stream, ut every time i use ```_mediaRecorder = MediaRecorder();``` it throws the error below:

```
E/flutter ( 5123): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'MediaRecorderNative' is not a subtype of type 'MediaRecorder'
E/flutter ( 5123): #0      new MediaRecorder (package:flutter_webrtc/src/media_recorder.dart:8:31)
E/flutter ( 5123): #1      _CallSampleState.startRecord (package:flutter_webrtc_demo/src/call_sample/call_sample.dart:144:22)
E/flutter ( 5123): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter ( 5123): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter ( 5123): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 5123): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter ( 5123): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 5123): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 5123): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 5123): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 5123): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 5123): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 5123): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 5123): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 5123): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 5123): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 5123): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5123): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5123): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5123): #19     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter ( 5123): #20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 5123): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 5123): #22     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter ( 5123): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter ( 5123): 
```

**To Reproduce**

1. I used [webrtc-demo](https://github.com/flutter-webrtc/flutter-webrtc-demo).
2. Add a record button to call_sample.dart
3. Add a function and initialize a local field 
      ```_mediaRecorder = MediaRecorder();```  

**Expected behavior**

The recording process must be started.

**Platform information**

* **Flutter version**: 
```[✓] Flutter (Channel stable, v1.17.0-4.0.pre.10, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0-4.0.pre.10 at /media/ali/develop/DeveloperStuffs/Flutter/flutter
    • Framework revision d9a506cee6 (3 months ago), 2020-07-18 05:47:21 +0430
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /media/ali/develop/DeveloperStuffs/Android.SDK.Tools.Bundle.v24.4.1
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /media/ali/develop/DeveloperStuffs/Android.SDK.Tools.Bundle.v24.4.1
    • Java binary at: /home/ali/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/ali/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • 192.168.56.101:5555 • 192.168.56.101:5555 • android-x86 • Android 9 (API 28)

! Doctor found issues in 1 category.
```
* **Plugin version**: flutter_webrtc: ^0.4.0
* **OS**: android
* **OS version**: 9.0-API28- Running on genymotion emulator

**Comment by ali-heidari** [comment]
Okay... I tried a little bit and made it work.

```dart
import 'package:flutter_webrtc/src/native/media_recorder_impl.dart';

// ...

MediaRecorderNative _mediaRecorder;

// ...

_mediaRecorder = MediaRecorderNative();

// ...
```

But the question is, Is it the solution?(I don't think so...)

**Comment by wer-mathurin** [comment]
@ali-heidari 
I'm able to reproduce the problem.  And identified the problem.  Will release a patch soon.

**Comment by wer-mathurin** [comment]
@ali-heidari You can look at the master branch in the mean time @cloudwebrtc release a new version of the library.
