### ISSUE TITLE
captureFrame on Android

### ISSUE THREAD

**Issue by tlevis** [flutter-webrtc/flutter-webrtc#463]
I'm trying to capture frame from stream on Android with:
`var test = await _remoteRenderer.srcObject.getVideoTracks()[0].captureFrame();`

and I'm getting this error:

```
E/MethodChannel#FlutterWebRTC.Method( 1920): Failed to handle method call
E/MethodChannel#FlutterWebRTC.Method( 1920): java.lang.NullPointerException
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at java.io.File.<init>(File.java:282)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:511)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/MethodChannel#FlutterWebRTC.Method( 1920): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/flutter ( 1920): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter ( 1920): 	at java.io.File.<init>(File.java:282)
E/flutter ( 1920): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:511)
E/flutter ( 1920): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 1920): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 1920): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter ( 1920): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 1920): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/flutter ( 1920): 	at android.os.Looper.loop(Looper.java:144)
E/flutter ( 1920): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/flutter ( 1920): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 1920): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/flutter ( 1920): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/flutter ( 1920): )
E/flutter ( 1920): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 1920): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 1920): <asynchronous suspension>
E/flutter ( 1920): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 1920): #3      MediaStreamTrackNative.captureFrame (package:flutter_webrtc/src/native/media_stream_track_impl.dart:75:21)
E/flutter ( 1920): #4      GameViewerState.capture (package:snoocare_viewer_app/pages/game_viewer.dart:116:70)
E/flutter ( 1920): #5      GameViewerState.build.<anonymous closure> (package:snoocare_viewer_app/pages/game_viewer.dart:181:35)
E/flutter ( 1920): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 1920): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 1920): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 1920): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 1920): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 1920): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 1920): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 1920): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 1920): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 1920): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 1920): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 1920): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 1920): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter ( 1920): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 1920): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 1920): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 1920): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 1920): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 1920): #24     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 1920): #25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 1920): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 1920): #27     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 1920): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

What I'm doing wrong?
Thanks.

**Comment by carman247** [comment]
Hi, I'm not 100% certain but I had to create a file and then use that file's path in the captureFrame method. Then it worked. However, my images are appearing desaturated, and I've opened an issue on here for that.

e.g. 

```
import 'package:path_provider/path_provider.dart';

Directory _directory;
Path _path;
File _file;
MediaStreamTrack _localVideoTrack;

// Find video tracks
final videoTracks = localStream.getVideoTracks();
// Set MediaStreamTrack
_localVideoTrack = videoTracks[0];
// Get application directory
_directory = await getApplicationDocumentsDirectory();
// Set path
_path = _directory.path;

 // Create file
_imageFile = await File('$_path/streamSnapshot/snapshot.jpeg').create(recursive: true);

// Capture frame
await _localVideoTrack.captureFrame(_imageFile.path);
```
