### ISSUE TITLE
SurfaceTextureHelper: main create failure. crashing at xiaomi

### ISSUE THREAD

**Issue by lxl518000** [flutter-webrtc/flutter-webrtc#499]
**Describe the bug**
2021-03-18 15:26:47.934 27501-27589/com.app.block_app I/flutter: imim:设置selfId:15@554103
2021-03-18 15:26:47.937 27501-27501/com.app.block_app I/org.webrtc.Logging: EglRenderer: Initializing EglRenderer
2021-03-18 15:26:47.939 27501-30590/com.app.block_app I/org.webrtc.Logging: EglRenderer: EglBase.create shared context
2021-03-18 15:26:47.941 27501-30590/com.app.block_app I/org.webrtc.Logging: EglBase14Impl: Using OpenGL ES version 2
2021-03-18 15:26:47.947 27501-27501/com.app.block_app I/org.webrtc.Logging: EglRenderer: Initializing EglRenderer
2021-03-18 15:26:47.948 27501-27589/com.app.block_app I/flutter: 开始响铃
2021-03-18 15:26:47.949 27501-30591/com.app.block_app I/org.webrtc.Logging: EglRenderer: EglBase.create shared context
2021-03-18 15:26:47.951 27501-30591/com.app.block_app I/org.webrtc.Logging: EglBase14Impl: Using OpenGL ES version 2
2021-03-18 15:26:47.963 27501-27501/com.app.block_app I/FlutterWebRTCPlugin: getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
2021-03-18 15:26:47.964 27501-27501/com.app.block_app I/FlutterWebRTCPlugin: getUserMedia(video): com.cloudwebrtc.webrtc.utils.ConstraintsMap@560b65b
2021-03-18 15:26:47.975 27501-27501/com.app.block_app D/FlutterWebRTCPlugin: Creating video capturer using Camera1 API.
2021-03-18 15:26:47.979 27501-27501/com.app.block_app I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
2021-03-18 15:26:47.983 27501-27501/com.app.block_app I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
2021-03-18 15:26:47.983 27501-27501/com.app.block_app I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
2021-03-18 15:26:47.989 27501-27501/com.app.block_app I/org.webrtc.Logging: Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
2021-03-18 15:26:48.004 27501-27501/com.app.block_app I/org.webrtc.Logging: Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
2021-03-18 15:26:48.008 27501-27501/com.app.block_app I/org.webrtc.Logging: Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
2021-03-18 15:26:48.008 27501-27501/com.app.block_app D/FlutterWebRTCPlugin: Create front camera Camera 1, Facing front, Orientation 270 succeeded
2021-03-18 15:26:48.012 27501-30592/com.app.block_app I/org.webrtc.Logging: EglBase14Impl: Using OpenGL ES version 2
2021-03-18 15:26:48.013 27501-30592/com.app.block_app E/org.webrtc.Logging: SurfaceTextureHelper: main create failure
2021-03-18 15:26:48.013 27501-30592/com.app.block_app E/org.webrtc.Logging: SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003
2021-03-18 15:26:48.015 27501-30592/com.app.block_app E/org.webrtc.Logging: SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:282)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:78)
        at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:215)
        at org.webrtc.EglBase$-CC.create(EglBase.java:158)
        at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:187)
        at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:33)
        at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:75)
        at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:70)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-03-18 15:26:48.016 27501-27501/com.app.block_app D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2021-03-18 15:26:48.019 27501-27501/com.app.block_app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.block_app, PID: 27501
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler org.webrtc.SurfaceTextureHelper.getHandler()' on a null object reference
        at org.webrtc.CameraCapturer.initialize(CameraCapturer.java:241)
        at org.webrtc.Camera1Capturer.initialize(Camera1Capturer.java:15)
        at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserVideo(GetUserMediaImpl.java:674)
        at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:569)
        at com.cloudwebrtc.webrtc.GetUserMediaImpl.access$000(GetUserMediaImpl.java:83)
        at com.cloudwebrtc.webrtc.GetUserMediaImpl$1.invoke(GetUserMediaImpl.java:422)
        at com.cloudwebrtc.webrtc.GetUserMediaImpl.lambda$requestPermissions$0(GetUserMediaImpl.java:747)
        at com.cloudwebrtc.webrtc.-$$Lambda$GetUserMediaImpl$e6a27aJzTGYN6IMKIdphyl2WNqo.invoke(Unknown Source:6)
        at com.cloudwebrtc.webrtc.utils.PermissionUtils$1.onReceiveResult(PermissionUtils.java:102)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
2021-03-18 15:26:48.053 27501-27501/com.app.block_app I/Process: Sending signal. PID: 27501 SIG: 9

**To Reproduce**

**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by thammaknot** [comment]
Did you find any workaround or fix?
