### ISSUE TITLE
Displaying tracks in unified plan - only one track is being displayed all other tracks are been disposed

### ISSUE THREAD

**Issue by igala** [flutter-webrtc/flutter-webrtc#503]
**Describe the bug**

When subscribing publishers in video room I get their tracks and I render the tracks one by one and only the last track is valid and being presented all the the other tracks are not valid and apparently looks like are being disposed by the native part.

The error I get is:

2021-03-27 04:15:02.236 19787-19816/com.example.galaxy_mobile E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, MediaStreamTrack has been disposed., null, java.lang.IllegalStateException: MediaStreamTrack has been disposed.
        at org.webrtc.MediaStreamTrack.checkMediaStreamTrackExists(MediaStreamTrack.java:120)
        at org.webrtc.MediaStreamTrack.getNativeMediaStreamTrack(MediaStreamTrack.java:114)
        at org.webrtc.VideoTrack.addSink(VideoTrack.java:40)
        at com.cloudwebrtc.webrtc.FlutterRTCVideoRenderer.tryAddRendererToVideoTrack(FlutterRTCVideoRenderer.java:203)
        at com.cloudwebrtc.webrtc.FlutterRTCVideoRenderer.setVideoTrack(FlutterRTCVideoRenderer.java:176)
        at com.cloudwebrtc.webrtc.FlutterRTCVideoRenderer.setStream(FlutterRTCVideoRenderer.java:153)
        at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:428)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

* **Flutter version**:  1.22.6
* **Plugin version**: 0.5.8
* **OS**: 
* **OS version**: Android version 9

**Comment by huoda1237** [comment]
Hello, I also encountered this problem. Have you solved it?

**Comment by huoda1237** [comment]
I modified the ‘onAddTrack’ method as follows:


@Override
  public void onAddTrack(RtpReceiver receiver, MediaStream[] mediaStreams) {
      Log.d(TAG, "onAddTrack");
      // For unified-plan
      if(this.configuration.sdpSemantics == PeerConnection.SdpSemantics.UNIFIED_PLAN) {
          ConstraintsMap params = new ConstraintsMap();
          ConstraintsArray streams = new ConstraintsArray();
          for(int i = 0; i< mediaStreams.length; i++){
              MediaStream stream = mediaStreams[i];
              streams.pushMap(new ConstraintsMap(mediaStreamToMap(stream)));
          }

          params.putString("event", "onTrack");
          params.putArray("streams", streams.toArrayList());
          params.putMap("track", mediaTrackToMap(receiver.track()));
          params.putMap("receiver", rtpReceiverToMap(receiver));

          List<RtpTransceiver> transceivers = peerConnection.getTransceivers();
          for( RtpTransceiver transceiver : transceivers ) {
              if(transceiver.getReceiver() != null && receiver.id().equals(transceiver.getReceiver().id())) {
                  String transceiverId = transceiver.getMid();
                  if(null == transceiverId) {
                      transceiverId = stateProvider.getNextStreamUUID();
                  }
                  params.putMap("transceiver", transceiverToMap(transceiverId, transceiver));
              }
          }
          remoteTracks.put(receiver.track().id(), receiver.track());
          sendEvent(params);
      } else {
          // for plan-b
          for (MediaStream stream : mediaStreams) {
              String streamId = stream.getId();
              MediaStreamTrack track = receiver.track();
              ConstraintsMap params = new ConstraintsMap();
              params.putString("event", "onAddTrack");
              params.putString("streamId", streamId);
              params.putString("ownerTag", id);
              params.putString("trackId", track.id());

              String trackId = track.id();
              ConstraintsMap trackInfo = new ConstraintsMap();
              trackInfo.putString("id", trackId);
              trackInfo.putString("label", track.kind());
              trackInfo.putString("kind", track.kind());
              trackInfo.putBoolean("enabled", track.enabled());
              trackInfo.putString("readyState", track.state().toString());
              trackInfo.putBoolean("remote", true);
              params.putMap("track", trackInfo.toMap());
              sendEvent(params);
          }
      }
  }

it   worked！！！！！

**Comment by robvr** [comment]
@huoda1237 Is the file that you modified part of the library?
