### ISSUE TITLE
部分机型录屏崩溃

### ISSUE THREAD

**Issue by tygm** [flutter-webrtc/flutter-webrtc#525]
**Describe the bug**
机型lenovo TB 8705N录屏崩溃。部分报错信息：
```
E/MediaCodec(17824): Codec reported err 0x80001005, actionCode 0, while in state 0
E/ACodec  (17824): [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)
E/ACodec  (17824): signalError(omxError 0x80001005, internalError -2147483648)
E/MediaCodec(17824): Codec reported err 0x80001005, actionCode 0, while in state 0
E/ACodec  (17824): [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)
E/ACodec  (17824): signalError(omxError 0x80001005, internalError -2147483648)
E/MediaCodec(17824): Codec reported err 0x80001005, actionCode 0, while in state 0
E/ACodec  (17824): [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)
E/ACodec  (17824): signalError(omxError 0x80001005, internalError -2147483648)
E/MediaCodec(17824): Codec reported err 0x80001005, actionCode 0, while in state 0
E/AndroidRuntime(17824): FATAL EXCEPTION: VideoFileRendererRenderThread
E/AndroidRuntime(17824): Process: com.zyt.tijianapp, PID: 17824
E/AndroidRuntime(17824): java.lang.IllegalStateException
E/AndroidRuntime(17824): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/AndroidRuntime(17824): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
E/AndroidRuntime(17824): 	at com.cloudwebrtc.webrtc.record.VideoFileRenderer.drainEncoder(VideoFileRenderer.java:163)
E/AndroidRuntime(17824): 	at com.cloudwebrtc.webrtc.record.VideoFileRenderer.renderFrameOnRenderThread(VideoFileRenderer.java:122)
E/AndroidRuntime(17824): 	at com.cloudwebrtc.webrtc.record.VideoFileRenderer.lambda$onFrame$1$VideoFileRenderer(VideoFileRenderer.java:113)
E/AndroidRuntime(17824): 	at com.cloudwebrtc.webrtc.record.-$$Lambda$VideoFileRenderer$RO0yjS7ifL0yewatqGTRJDUOl-E.run(Unknown Source:4)
E/AndroidRuntime(17824): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(17824): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(17824): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(17824): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ACodec  (17824): [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)
E/ACodec  (17824): signalError(omxError 0x80001005, internalError -2147483648)
E/MediaCodec(17824): Codec reported err 0x80001005, actionCode 0, while in state 0
E/ACodec  (17824): [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)
E/ACodec  (17824): signalError(omxError 0x80001005, internalError -2147483648)
E/MediaCodec(17824): Codec reported err 0x80001005, actionCode 0, while in state 0
E/ACodec  (17824): [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)
```

**To Reproduce**
机型lenovo TB 8705N录屏，调用getDisplayMedia+mediaRecorder进行录制视频
**Expected behavior**
录屏正常
**Platform information**

* **Flutter version**: 2.0.4
* **Plugin version**:0.6.3
* **OS**: android
* **OS version**:android 9.0

**Comment by liuhangb** [comment]
之前碰到过类似的，分辨率配置过大有些机型不支持就会崩溃
