### ISSUE TITLE
Screen Capture Android onResume: Cannot start already started MediaProjection

### ISSUE THREAD

**Issue by XuanTung95** [flutter-webrtc/flutter-webrtc#551]
**Describe the bug**
```
E/AndroidRuntime( 8090): FATAL EXCEPTION: main
E/AndroidRuntime( 8090): Process: com.github.pion.ion.ion_flutter_app, PID: 8090
E/AndroidRuntime( 8090): java.lang.RuntimeException: Unable to resume activity {com.github.pion.ion.ion_flutter_app/com.github.pion.ion.ion_flutter_app.MainActivity}: java.lang.IllegalStateException: Cannot start already started MediaProjection
E/AndroidRuntime( 8090): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3805)
E/AndroidRuntime( 8090): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3845)
E/AndroidRuntime( 8090): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1773)
E/AndroidRuntime( 8090): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8090): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 8090): 	at android.app.ActivityThread.main(ActivityThread.java:7000)
E/AndroidRuntime( 8090): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8090): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
E/AndroidRuntime( 8090): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
E/AndroidRuntime( 8090): Caused by: java.lang.IllegalStateException: Cannot start already started MediaProjection
E/AndroidRuntime( 8090): 	at android.os.Parcel.readException(Parcel.java:2037)
E/AndroidRuntime( 8090): 	at android.os.Parcel.readException(Parcel.java:1975)
E/AndroidRuntime( 8090): 	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:140)
E/AndroidRuntime( 8090): 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:69)
E/AndroidRuntime( 8090): 	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:165)
E/AndroidRuntime( 8090): 	at org.webrtc.ScreenCapturerAndroid.startCapture(ScreenCapturerAndroid.java:114)
E/AndroidRuntime( 8090): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.reStartCamera(GetUserMediaImpl.java:1029)
E/AndroidRuntime( 8090): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.reStartCamera(MethodCallHandlerImpl.java:1663)
E/AndroidRuntime( 8090): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin$LifeCycleObserver.onResume(FlutterWebRTCPlugin.java:184)
E/AndroidRuntime( 8090): 	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:42)
E/AndroidRuntime( 8090): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
E/AndroidRuntime( 8090): 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
E/AndroidRuntime( 8090): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
E/AndroidRuntime( 8090): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
E/AndroidRuntime( 8090): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
E/AndroidRuntime( 8090): 	at io.flutter.embedding.android.FlutterActivity.onResume(FlutterActivity.java:541)
E/AndroidRuntime( 8090): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1363)
E/AndroidRuntime( 8090): 	at android.app.Activity.performResume(Activity.java:7485)
E/AndroidRuntime( 8090): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3780)
E/AndroidRuntime( 8090): 	... 8 more
```
**To Reproduce**
1 - Start screen capture on android.
2 - Send app to background
3 - Open app

**Platform information**
Android 8.1

**Comment by danteCarvalho** [comment]
I have the same problem, when i change or hide the app then go back i get this exception

**Comment by XuanTung95** [comment]
> I have the same problem, when i change or hide the app then go back i get this exception

The fix is merged. You could test with master branch now.
