### ISSUE TITLE
Error: UnimplementedError Flutter WEB

### ISSUE THREAD

**Issue by NavDevP** [flutter-webrtc/flutter-webrtc#576]
Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:59712/dart_sdk.js:5348:11)
    at Function.getCallbackHandle (http://localhost:59712/dart_sdk.js:134850:17)
    at initialize (http://localhost:59712/packages/flutter_downloader/src/downloader.dart.lib.js:78:58)
    at initialize.next (<anonymous>)
    at runBody (http://localhost:59712/dart_sdk.js:39250:34)
    at Object._async [as async] (http://localhost:59712/dart_sdk.js:39281:7)
    at Function.initialize (http://localhost:59712/packages/flutter_downloader/src/downloader.dart.lib.js:75:20)
    at main$ (http://localhost:59712/packages/name/myapp//screens/account_settings_screen.dart.lib.js:46697:42)
    at main$.next (<anonymous>)
    at http://localhost:59712/dart_sdk.js:39230:33
    at _RootZone.runUnary (http://localhost:59712/dart_sdk.js:39087:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:59712/dart_sdk.js:34073:29)
    at handleValueCallback (http://localhost:59712/dart_sdk.js:34633:49)
    at Function._propagateToListeners (http://localhost:59712/dart_sdk.js:34671:17)
    at _Future.new.[_completeWithValue] (http://localhost:59712/dart_sdk.js:34513:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59712/dart_sdk.js:34536:35)
    at Object._microtaskLoop (http://localhost:59712/dart_sdk.js:39374:13)
    at _startMicrotaskLoop (http://localhost:59712/dart_sdk.js:39380:13)
    at http://localhost:59712/dart_sdk.js:34887:9

**Comment by Hamzadildar** [comment]
Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:58522/dart_sdk.js:5063:11)
    at Function.getCallbackHandle (http://localhost:58522/dart_sdk.js:138816:17)
    at initialize (http://localhost:58522/packages/flutter_downloader/src/downloader.dart.lib.js:77:58)
    at initialize.next (<anonymous>)
    at runBody (http://localhost:58522/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:58522/dart_sdk.js:40242:7)
    at Function.initialize (http://localhost:58522/packages/flutter_downloader/src/downloader.dart.lib.js:74:20)
    at main$ (http://localhost:58522/packages/daxssapp/main.dart.lib.js:319:42)
    at main$.next (<anonymous>)
    at runBody (http://localhost:58522/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:58522/dart_sdk.js:40242:7)
    at main$ (http://localhost:58522/packages/daxssapp/main.dart.lib.js:316:18)
    at main (http://localhost:58522/web_entrypoint.dart.lib.js:36:29)
    at main.next (<anonymous>)
    at http://localhost:58522/dart_sdk.js:40192:33
    at _RootZone.runUnary (http://localhost:58522/dart_sdk.js:40062:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:58522/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:58522/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:58522/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:58522/dart_sdk.js:35437:23)
    at http://localhost:58522/dart_sdk.js:34617:46
    at _RootZone.runUnary (http://localhost:58522/dart_sdk.js:40062:59)
    at _FutureListener.then.handleValue (http://localhost:58522/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:58522/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:58522/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:58522/dart_sdk.js:35437:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58522/dart_sdk.js:35458:35)
    at Object._microtaskLoop (http://localhost:58522/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:58522/dart_sdk.js:40336:13)
    at http://localhost:58522/dart_sdk.js:35811:9

**Comment by cloudwebrtc** [comment]
Please update to the latest stable channel.
