### ISSUE TITLE
Blank screen but sometimes it works

### ISSUE THREAD

**Issue by pulstar** [flutter-webrtc/flutter-webrtc#579]
**Describe the bug**

I did setup the Signaling and the TURN server and they are fine and working. I configured the flutter_webrtc_demo and compiled it. I chose the P2P Call Sample and it connected well. I can see both devices in the list. But when I try to connect two devices using different wifi connections, it shows only a blank screen. But sometimes it works, sometimes it takes few a seconds and works, but most of the time it don't. Also, when it connect, only one side have image. Local image shows fine on both devices. In the logs I got the error below, but I have no idea of what it is about.

PlatformException(videoRendererSetSrcObject, videoRendererSetSrcObject(): render [48] not found !, null, null) [2021-06-02 17:35:58]
I/flutter ( 9163): Exception: PlatformException(videoRendererSetSrcObject, videoRendererSetSrcObject(): render [48] not found !, null, null)
I/flutter ( 9163): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
I/flutter ( 9163): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
I/flutter ( 9163): <asynchronous suspension>
I/flutter ( 9163): #2      RTCVideoRendererNative.srcObject=.<anonymous closure> (package:flutter_webrtc/src/native/rtc_video_renderer_impl.dart)
I/flutter ( 9163): <asynchronous suspension>
D/MediaConstraintsUtils( 9163): mandatory constraints are not a map
D/MediaConstraintsUtils( 9163): optional constraints are not an array
I/org.webrtc.Logging( 9163): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging( 9163): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging( 9163): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging( 9163): WebRtcAudioEffectsExternal: setNS(true)
I/org.webrtc.Logging( 9163): NetworkMonitor: Start monitoring with native observer 1673512896
I/org.webrtc.Logging( 9163): NetworkMonitorAutoDetect: Network becomes available: 100
D/FlutterWebRTCPlugin( 9163): onIceGatheringChangeGATHERING
I/flutter ( 9163): Bad state: StreamSink is closed [2021-06-02 17:35:58]
I/flutter ( 9163): #0      _StreamSinkImpl.add (dart:_http/http_impl.dart:632:7)
I/flutter ( 9163): #1      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1223:11)
I/flutter ( 9163): #2      SimpleWebSocket.send (package:insignia_media/src/webrtc/websocket.dart:36:20)
I/flutter ( 9163): #3      Signaling._send (package:insignia_media/src/webrtc/signaling.dart:489:18)
I/flutter ( 9163): #4      Signaling._createOffer (package:insignia_media/src/webrtc/signaling.dart:449:12)
I/flutter ( 9163): <asynchronous suspension>

* **Flutter version**: 
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [versÃ£o 10.0.19042.985], locale pt-BR)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (5 available)
    • Vivo XI (mobile)     • PRUCHYWGG6HYSK4H • android-arm64  • Android 9 (API 28)
    • Moto X Play (mobile) • ZY223DPJLM       • android-arm    • Android 7.1.1 (API 25)
    • Windows (desktop)    • windows          • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.985]
    • Chrome (web)         • chrome           • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)           • edge             • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.

* **Plugin version**: 0.6.4
* **OS**: Android
* **OS version**: 9.0

**Comment by SteveFunso** [comment]
You'll have to create a turn server (refer to this [implementing flutterwebrtc](https://larrylisky.com/2020/05/22/implementing-flutter-webrtc-client-and-server/)  and [create a turn server](https://linuxize.com/post/how-to-install-go-on-ubuntu-18-04/) ) then update the ice servers configuration in the signaling.dart file of the client code.
