### ISSUE TITLE
Android is generating exception on 20 media streams.

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [flutter-webrtc/flutter-webrtc#611]
I am implementing an app to show remote videos,
Android is generating below exception while recieving 20 video streams even without rendering any streams.
````
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging( 8724): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
E/org.webrtc.Logging( 8724): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging( 8724): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
````
using flutter_webrtc - 0.6.5

flutter doctor -v
````
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.3.1 20E241 darwin-x64, locale en-IN)
    • Flutter version 2.2.2 at /Users/<User>/Library/Flutter/sdk/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/<User>/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • M2010J19CI (mobile) • 20ffb7620c20       • android-arm64  • Android 10 (API 29)
    • M2010J19CI (mobile) • 192.168.81.28:5555 • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome             • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

````

**Comment by MohamedRisaldarTA** [comment]
Hey,
Do we have any update on this...

**Comment by ycherniavskyi** [comment]
Your issue is related to the `webrtc` library, but no its wrapper what `flutter-webrtc` is actually is.

And when you wrote that you have the issue with 20 media streams on a mobile device I think you left within 1-2% of whole users of this package and 5-10% users of the `webrtc` library. So don't expect to get any valuable advice for such a generic complaints.

But event from your stack trace I can see that there is some video decoder issue, so I can advise you next steps:
* find the maximum media streams which device can process before the crash
* try different android phones to detect if this issue hardware related
* and finally try to tune and build a custom version of `webrtc` library
