### ISSUE TITLE
Support switching Audio Track on a MediaStream

### ISSUE THREAD

**Issue by kNoAPP** [flutter-webrtc/flutter-webrtc#651]
**Is your feature request related to a problem? Please describe.**
I'm building an audio/video manager settings page for my iOS/Android/Mac project. I can display all available audio/video devices just fine. I can select and switch video devices just fine. But when I switch audio devices, the operation throws at a native level.

**Describe the solution you'd like**
I'd like a supported way to change my audio input device on a MediaStream, similar to Helper.switchCamera. Or, at minimum, when I add an audio track to a MediaStream, I'd like this exception below handled as expected.

**Describe alternatives you've considered**
While the Helper's camera switching is great for iOS/Android, on MacOS, this is a different story. Since I could have like 17 cameras or audio devices plugged in, I need a way to select which device I want to use. I've managed to support camera switching using pure dart. But doing the same with audio fails.

The only alternative solution I can think of is to create an entirely new MediaStream with the audio source id constraint. But being a completely new stream, this increases my problem complexity significantly.

**Additional context**
Here's the exception being thrown (for Android):
```
I/FlutterWebRTCPlugin(22497): getUserMedia(audio): mandatory: [], optional: [sourceId: audio-1]
D/FlutterWebRTCPlugin(22497): MediaStream id: f432fbbd-a0b5-419f-b833-34740faee0c6
D/FlutterWebRTCPlugin(22497): setVolume(): 9a4751e4-7fb4-49b6-8d10-b86d7c2c79d5,5.0
E/MethodChannel#FlutterWebRTC.Method(22497): Failed to handle method call
E/MethodChannel#FlutterWebRTC.Method(22497): java.lang.ClassCastException: org.webrtc.AudioTrack cannot be cast to org.webrtc.VideoTrack
E/MethodChannel#FlutterWebRTC.Method(22497): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:354)
E/MethodChannel#FlutterWebRTC.Method(22497): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#FlutterWebRTC.Method(22497): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#FlutterWebRTC.Method(22497): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[...]
```

Code snippet of what's triggering this exception:
```dart
// Stop only the audio tracks so that we can recapture audio track
    List<MediaStreamTrack> toRemove = [];
    stream!.getAudioTracks().forEach((track) => toRemove.add(track));
    for (MediaStreamTrack track in toRemove) {
      await stream!.removeTrack(track);
      await track.stop();
    }

    Map<String, dynamic> mediaConstraints = {
      'audio': {
        'optional': [
          {
            'sourceId': deviceId,
          },
        ],
      },
      'video': false, // No need to capture video here
    };

    MediaStream _stream =
        await navigator.mediaDevices.getUserMedia(mediaConstraints);
    await stream!.addTrack(_stream.getAudioTracks()[0]);
```

**Comment by cloudwebrtc** [comment]
Looks like a bug.
```
E/MethodChannel#FlutterWebRTC.Method(22497): java.lang.ClassCastException: org.webrtc.AudioTrack cannot be cast to org.webrtc.VideoTrack
E/MethodChannel#FlutterWebRTC.Method(22497): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:354)
```

**Comment by AndreXi** [comment]
I am facing the same issue right now, I will make a PR to fix the exception error. 

I also thought that the exception was breaking the audio track at native level, but my app just seems to be fine, looking at the code the track is added before the method call fails.
