### ISSUE TITLE
Android device failed to share screen to the other android device , use replaceTrack method, other android device report deliverDecodedFrame failed

### ISSUE THREAD

**Issue by telinx** [flutter-webrtc/flutter-webrtc#668]
**Describe the bug**
Android device A (replaceTrack ) share screen to android  device B, B report error, but A share screen to ios or pc web is okay.
```
E/org.webrtc.Logging(16235): AndroidVideoDecoder: deliverDecodedFrame failed
E/org.webrtc.Logging(16235): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging(16235): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging(16235):    at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging(16235):    at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
E/org.webrtc.Logging(16235):    at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:73)
E/org.webrtc.Logging(16235):    at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:389)
E/org.webrtc.Logging(16235):    at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:373)
E/org.webrtc.Logging(16235): AndroidVideoDecoder: deliverDecodedFrame failed
```
code
```
 ...
 screenShareStream();
 ...
 /*
  * 创建屏幕共享媒体
  * */
  Future<MediaStream> screenShareStream() async {
    if (Platform.isAndroid) {
      await startForegroundService();
    }
    Map<String, dynamic> mediaConstraints = <String, dynamic>{
      'audio': true,
      'video': {
        'mandatory': {
          'minWidth': '640',
          'minHeight': '480',
          'minFrameRate': '30',
        },
        'facingMode': 'user',
        'optional': [],
      },
    };
    MediaStream stream = await navigator.mediaDevices.getDisplayMedia(mediaConstraints);
    localScreenStream = stream;
    onLocalStream(stream);
    
    await myPeerConnection.getSenders().then((senders) {
      senders.forEach((element) {
        if (element.track!.kind == 'video') {
          element.replaceTrack(stream.getVideoTracks()[0]);
          // element.replaceTrack();
        }
      });
    });
    return stream;
  }
```
webrtc doc show replaceTrack don't need to negotiation.
expect a reply, thank you.

**To Reproduce**

**Expected behavior**
Android device A share screen to android  device B is okay too
**Platform information**
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.17763.1], locale zh-CN)
    • Flutter version 2.2.3 at F:\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: F:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Users\user\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at F:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • M2007J22C (mobile) • i75l89fazlnjwcr8 • android-arm64  • Android 10 (API 29)
    • M2007J22C (mobile) • ovbq6t5pm7ljz549 • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 91.0.4472.124
```
* **Flutter version**:  Channel stable, 2.2.3
* **Plugin version**: 0.6.5
* **OS**:  Android 10   Android 11
* **OS version**:

**Comment by TBYSKY** [comment]
Did you solve it, I have the same problem
