### ISSUE TITLE
I am not able to audio and video of local and remote peer

### ISSUE THREAD

**Issue by vishalsync** [flutter-webrtc/flutter-webrtc#682]
**Describe the bug**

**To Reproduce**
E/AndroidRuntime(12500): FATAL EXCEPTION: VideoFileRendererRenderThread
E/AndroidRuntime(12500): Process: com.example.flutter_webrtc_demo, PID: 12500
E/AndroidRuntime(12500): java.lang.IllegalStateException: Can't stop due to wrong state.
E/AndroidRuntime(12500): 	at android.media.MediaMuxer.stop(MediaMuxer.java:457)
E/AndroidRuntime(12500): 	at com.cloudwebrtc.webrtc.record.VideoFileRenderer.lambda$release$3$VideoFileRenderer(VideoFileRenderer.java:145)
E/AndroidRuntime(12500): 	at com.cloudwebrtc.webrtc.record.-$$Lambda$VideoFileRenderer$NuSB8LuOREvb9PEhuce_zNtzgVs.run(Unknown Source:2)
E/AndroidRuntime(12500): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(12500): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12500): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(12500): 	at android.os.HandlerThread.run(HandlerThread.java:65)
I/flutter (12500): stopCallRecording = null
D/ViewRootImpl@b74814f[MainActivity](12500): MSG_WINDOW_FOCUS_CHANGED 0 1

**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by laxkarparas1** [comment]
did you find any solution for the same ??
