### ISSUE TITLE
MissingPluginException on Windows (No implementation found for method listen on channel FlutterWebRTC/dataChannelEvent06BAE32C-...)

### ISSUE THREAD

**Issue by yeewang** [flutter-webrtc/flutter-webrtc#706]
**Describe the bug**

Trying this plugin in the ion-app-flutter. 
When login to a meeting room, the below exception occurs.

```
======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel FlutterWebRTC/dataChannelEvent06BAE32C-2923-4388-BBA8-4F9BEB24438B0:
MissingPluginException(No implementation found for method listen on channel FlutterWebRTC/dataChannelEvent06BAE32C-2923-4388-BBA8-4F9BEB24438B0)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================

```

**To Reproduce**
To use an app on Windows. When login to a meeting room, the below exception occurs.

**Expected behavior**
the event "FlutterWebRTC/dataChannelEvent06BAE32C-2923-4388-BBA8-4F9BEB24438B0" can be handled.

**Platform information**

* **Flutter version**: 2.5.1
* **Plugin version**:  0.6.7
* **OS**: Windows
* **OS version**: Windows 10

**Comment by cloudwebrtc** [comment]
Please try the last commit.

**Comment by PeterNjeim** [comment]
I've tried the latest commit and I'm still receiving the error. For some reason, this only occurs if I run the code from a Windows user, this does not happen on Android or web. This means that I can connect to a Windows user from a web or Android user, but not the other way around.

**Comment by imanabu** [comment]
This is happening again in June 11, 2024

[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22635.3720], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.6.2)
[√] Android Studio (version 2022.3)
[√] Android Studio (version 2023.3)
[√] IntelliJ IDEA Ultimate Edition (version 2024.1)
[√] VS Code (version 1.90.0)
[√] Connected device (3 available)
[√] Network resources

I do not know enough about where the cloud functions windows plug-in can be installed from.

My echo service is a simple echo back that happens immediately after logging in to ensure that function can call the backend. Works on web, MacOS and Android without a problem. Only on Windows (11).

```
A Dart VM Service on Windows is available at: http://127.0.0.1:58352/BnaoWr2c1EI=/
The Flutter DevTools debugger and profiler on Windows is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:58352/BnaoWr2c1EI=/
[ERROR:flutter/shell/common/shell.cc(1055)] The 'firebase_auth_plugin/id-token/[DEFAULT]' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method FirebaseFunctions#call on channel plugins.flutter.io/firebase_functions)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:22:24)
<asynchronous suspension>
#2      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:49:37)
<asynchronous suspension>
#3      AuthService.echo (package:tour/services/auth_service.dart:42:22)
<asynchronous suspension>
#4      _SignInState._handleAllSignIn (package:tour/widgets/sign_in/sign_in.dart:134:7)
<asynchronous suspension>
```
