### ISSUE TITLE
`flutter run` fails but running in Xcode is successful

### ISSUE THREAD

**Issue by roo0t** [flutter-webrtc/flutter-webrtc#755]
**Describe the bug**
Running Flutter app on iOS simulator by running command `flutter run` fails, giving the following output:

```
Running "flutter pub get" in test...                               726ms
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running pod install...                                             967ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_webrtc` from
    `.symlinks/plugins/flutter_webrtc/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_webrtc":
      In Podfile:
        flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`)

    Specs satisfying the `flutter_webrtc (from
    `.symlinks/plugins/flutter_webrtc/ios`)` dependency were found, but they
    required a higher minimum deployment target.

    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolut
    ion.rb:317:in `raise_error_unless_state'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolut
    ion.rb:299:in `block in unwind_for_conflict'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolut
    ion.rb:297:in `tap'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolut
    ion.rb:297:in `unwind_for_conflict'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolut
    ion.rb:682:in `attempt_to_activate'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolut
    ion.rb:254:in `process_topmost_state'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolut
    ion.rb:182:in `resolve'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolve
    r.rb:43:in `resolve'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolv
    er.rb:94:in `resolve'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/instal
    ler/analyzer.rb:1078:in `block in resolve_dependencies'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_i
    nterface.rb:64:in `section'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/instal
    ler/analyzer.rb:1076:in `resolve_dependencies'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/instal
    ler/analyzer.rb:124:in `analyze'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/instal
    ler.rb:416:in `analyze'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/instal
    ler.rb:241:in `block in resolve_dependencies'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_i
    nterface.rb:64:in `section'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/instal
    ler.rb:240:in `resolve_dependencies'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/instal
    ler.rb:161:in `install!'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/comman
    d/install.rb:52:in `run'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/claide-1.0.3/lib/claide/command.rb:33
    4:in `run'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/comman
    d.rb:52:in `run'
    /Users/rooot/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top
    (required)>'
    /Users/rooot/.rvm/gems/ruby-2.6.0/bin/pod:23:in `load'
    /Users/rooot/.rvm/gems/ruby-2.6.0/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `9.0` on target
    `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro.
```

However, when I run the same app from Xcode, it successfully launches on the simulator.

**To Reproduce**
1. Create a flutter app.
2. Add dependency to `flutter_webrtc` with command `flutter pub add flutter_webrtc`.
3. Open an iOS simulator and run the app with the command `flutter run`.

**Expected behavior**
Flutter app won't show up in the simulator and print errors. (as shown above)

**Platform information**
MacOS Big Sur 11.6
Xcode 13.0

* **Flutter version**: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale ko)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
[✓] VS Code (version 1.61.2)
[✓] Connected device (2 available)
    ! Error: rooot-mobile is not connected. Xcode will continue when
      rooot-mobile is connected. (code -13)

! Doctor found issues in 1 category.
```

* **Plugin version**:
0.7.0+hotfix.2

* **OS**: 
iOS

* **OS version**:
Simulator: iPhone 11 Pro (iOS 13.1)

**Comment by cloudwebrtc** [comment]
Please  modify `ios/Podfile`

Change
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
```
to
```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
```

https://github.com/flutter-webrtc/flutter-webrtc/blob/master/example/scripts/project_tools.sh#L36

**Comment by roo0t** [comment]
Thanks, @cloudwebrtc

I tried modifying `ios/Podfile` and now I have a different error message:

```
Running "flutter pub get" in test...                             1,196ms
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running pod install...                                           2,104ms
Running Xcode build...
Xcode build done.                                            3.5s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:5AF92FBD-C01E-4AD3-95AF-24D7F1BC6F4F, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:5C256100-2DE6-44F6-AF1A-47BE6A4536FF, OS:13.1, name:iPad Air (3rd generation) }
    { platform:iOS Simulator, id:24AAF547-D586-4F76-9229-A6F7E7C32089, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:E88BAD4B-D267-44C0-A2D2-4CC53BE21DDF, OS:13.1, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:39CE618A-73CE-41A7-9442-6738C6F7684C, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:299875F9-F86A-41B2-B597-16C5B68B9F00, OS:13.1, name:iPad Pro (11-inch) }
    { platform:iOS Simulator, id:F5D474BB-E829-476E-8B50-BEA509BC7AA6, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:87C2C767-9CCC-4089-A138-1C8F7552D29F, OS:13.1, name:iPad Pro (12.9-inch) (3rd generation) }
    { platform:iOS Simulator, id:DE40BB37-09E6-4D9C-A81B-4B1684E5130C, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:0FA51FC8-705F-407C-BFCA-866F559B2E79, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:B294F0E3-C55F-4717-A0A1-651813B3EA7B, OS:13.1, name:iPhone 8 }
    { platform:iOS Simulator, id:068419E2-FC8C-4C58-81BE-AC87EE209C7C, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:7B0CF607-3A20-4D97-BD77-6B2114873244, OS:13.1, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:3BECDC3D-4472-4C90-BDF4-8E4B531809F2, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:BD5AEC93-C354-45BB-9C61-A560292BE774, OS:13.1, name:iPhone 11 }
    { platform:iOS Simulator, id:9AF620A9-F722-4CDD-BE1F-DEF9D4AE1F10, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:3AF2EDB1-526E-444A-89F7-1D7E35122201, OS:13.1, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:09E0EFE3-BDFC-4114-B0A6-4B3CB1751412, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:7CC8095F-054B-4764-A70D-4E30CA3E4571, OS:13.1, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:1D726FFE-7DDC-4393-916B-B203A2629B54, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:71342D7D-5869-4406-B49E-923D5AA4DD34, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:BE31C266-C149-474D-8F35-BA25E4657AD1, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:4DFEE254-B2AD-45F1-B82B-018C997153BF, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:E50FEFF7-4B8B-43AE-A502-8E5BCB5E6F9E, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:2E2985C5-D975-4069-8A97-8EACF3C8CD05, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:A974917D-42F0-492D-8643-00CD37B2168E, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:39D9097E-D7BE-4351-93EF-DF83300E0058, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:49D7E374-51AC-4AE2-935F-BFB2E3DF03D9, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:A4AE0169-1602-48C9-8BCC-75D58ABCCECA, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:A6BDC85F-E503-4F6B-AC0D-8D39956E0F12, OS:15.0, name:iPod touch (7th generation) }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    { platform:iOS, id:00008030-000504E10C02802E, name:rooot-mobile }
    ** BUILD FAILED **


Xcode's output:
↳
    warning: [CP] Unable to find matching .xcframework slice in 'ios-arm64 ios-arm64_x86_64-simulator' for the current build architectures (arm64 x86_64 i386).
    /Users/rooot/Library/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.7.0+hotfix.2/ios/Classes/AudioUtils.m:2:9: fatal error: 'WebRTC/WebRTC.h' file not found
    #import <WebRTC/WebRTC.h>
            ^~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    note: Removed stale file '/Users/rooot/Library/Developer/Xcode/DerivedData/Runner-gflbparvepfdqhgowydgihwlwbbb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-AA17B9436CF36862F744D7E3.sh'

    /Users/rooot/dev/test/test/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Libyuv'
    from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.
```

By the way, if it is necessary to modify the Podfile to use the library, I think it should be added to the installation instruction.

**Comment by cloudwebrtc** [comment]
> By the way, if it is necessary to modify the Podfile to use the library, I think it should be added to the installation instruction.

Yeah, I forgot to add this, I will make it up, another error here seems to be caused by other reasons

**Comment by roo0t** [comment]
@cloudwebrtc 
If `.xcframework` you mentioned is `ios/Pods/WebRTC-SDK/WebRTC.xcframework` directory, then it does not have all the platforms. It contains only `ios-arm64`, `ios-arm64_x86_64-simulator`, and `macos-arm64_x86_64` subdirectories. If it is the problem, how can I fix it?

**Comment by cloudwebrtc** [comment]
You can remove the non-existent architecture in the build settings of Xcode.

**Comment by roo0t** [comment]
Thanks to [this post](https://stackoverflow.com/a/69543855/8051581), I could manage the issue by modifying the Podfile as follows:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |build_configuration|
      build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
    end
  end
end
```

**Comment by janhelwich** [comment]
The modification of the Podfile as described by @roo0t works for me too. Thanks

**Comment by ycherniavskyi** [comment]
It seems that the issue if resolved. The secants part of it is moved to [separate discussion](#1026).

**Comment by lyskouski** [comment]
Raised back with Flutter 3.13.6
