### ISSUE TITLE
Crash in v0.7.1

### ISSUE THREAD

**Issue by abhi-dasgupta** [flutter-webrtc/flutter-webrtc#781]
Crash after successful p2p connection when video starts

'''
[log] "<message id="RSQAFRUCE" type="headline" to="5150297-5662@chat.connectycube.com"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>5150293</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>5150297</callerID><callType>1</callType><sessionID>1b5d8b87-5e08-4c93-85f5-2caebd20444e</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>2.0.7</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>0</sdpMid><candidate>candidate:2505969574 1 udp 2122260223 192.168.31.29 41157 typ host generation 0 ufrag wj9X network-id 4 network-cost 10</candidate></iceCandidate></iceCandidates></extraParams></message>"
[log] ---Xmpp Sending:---
I/flutter (17491): CB-SDK: : sendIceCandidate, _sdp = CubeRTCSessionDescription: {sessionId = 1b5d8b87-5e08-4c93-85f5-2caebd20444e, callerId = 5150297, opponents = {5150293}, conferenceType = 1, userInfo = null}
I/flutter (17491): CB-SDK: : sendIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 1b5d8b87-5e08-4c93-85f5-2caebd20444e, callerId = 5150297, opponents = {5150293}, conferenceType = 1, userInfo = null}
I/flutter (17491): CB-SDK: : sendIceCandidate, _sdp = CubeRTCSessionDescription: {sessionId = 1b5d8b87-5e08-4c93-85f5-2caebd20444e, callerId = 5150297, opponents = {5150293}, conferenceType = 1, userInfo = null}
I/flutter (17491): CB-SDK: : sendIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 1b5d8b87-5e08-4c93-85f5-2caebd20444e, callerId = 5150297, opponents = {5150293}, conferenceType = 1, userInfo = null}
[log] "<message id="NVGWGDDCE" type="headline" to="5150297-5662@chat.connectycube.com"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>5150293</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>5150297</callerID><callType>1</callType><sessionID>1b5d8b87-5e08-4c93-85f5-2caebd20444e</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>2.0.7</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>0</sdpMid><candidate>candidate:559267639 1 udp 2122136831 ::1 43869 typ host generation 0 ufrag wj9X network-id 2</candidate></iceCandidate></iceCandidates></extraParams></message>"
[log] ---Xmpp Sending:---
[log] "<message id="ILYIPMSGK" type="headline" to="5150297-5662@chat.connectycube.com"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>5150293</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>5150297</callerID><callType>1</callType><sessionID>1b5d8b87-5e08-4c93-85f5-2caebd20444e</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>2.0.7</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>0</sdpMid><candidate>candidate:1510613869 1 udp 2122063615 127.0.0.1 41375 typ host generation 0 ufrag wj9X network-id 1</candidate></iceCandidate></iceCandidates></extraParams></message>"
[log] ---Xmpp Sending:---
[log] "<message id="PXSTVGJYN" type="headline" to="5150297-5662@chat.connectycube.com"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>5150293</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>5150297</callerID><callType>1</callType><sessionID>1b5d8b87-5e08-4c93-85f5-2caebd20444e</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>2.0.7</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>0</sdpMid><candidate>candidate:1737481681 1 tcp 1518217471 2409:4001:e1f:94a7::8c08:2b07 9 typ host tcptype active generation 0 ufrag wj9X network-id 3 network-cost 900</candidate></iceCandidate></iceCandidates></extraParams></message>"
[log] ---Xmpp Sending:---
[log] "<message id="FHAEVSKAE" type="headline" to="5150297-5662@chat.connectycube.com"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>5150293</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>5150297</callerID><callType>1</callType><sessionID>1b5d8b87-5e08-4c93-85f5-2caebd20444e</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>2.0.7</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>0</sdpMid><candidate>candidate:1876313031 1 tcp 1518157055 ::1 60133 typ host tcptype passive generation 0 ufrag wj9X network-id 2</candidate></iceCandidate></iceCandidates></extraParams></message>"
[log] ---Xmpp Sending:---
D/FlutterWebRTCPlugin(17491): CameraEventsHandler.onFirstFrameAvailable
[log] "<message id="SSESOQJQU" type="headline" to="5150297-5662@chat.connectycube.com"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>5150293</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>5150297</callerID><callType>1</callType><sessionID>1b5d8b87-5e08-4c93-85f5-2caebd20444e</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>2.0.7</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>0</sdpMid><candidate>candidate:344579997 1 tcp 1518083839 127.0.0.1 59473 typ host tcptype passive generation 0 ufrag wj9X network-id 1</candidate></iceCandidate></iceCandidates></extraParams></message>"
I/BufferQueueConsumer(17491): [SurfaceTexture-0-17491-3](this:0xbd486000,id:3,api:1,p:17491,c:17491) setDefaultBufferSize: width=720 height=1280
I/BufferQueueProducer(17491): [SurfaceTexture-2-17491-1](this:0xc1de6000,id:1,api:4,p:483,c:17491) queueBuffer: slot 0 is dropped, handle=0xe722e780
W/System.err(17491): java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Not implemented.
W/System.err(17491): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
W/System.err(17491): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
W/System.err(17491): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper.initEncode(SimulcastVideoEncoderFactoryWrapper.kt:109)
W/System.err(17491): Caused by: java.lang.UnsupportedOperationException: Not implemented.
W/System.err(17491): 	at org.webrtc.WrappedNativeVideoEncoder.initEncode(WrappedNativeVideoEncoder.java:22)
W/System.err(17491): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:107)
W/System.err(17491): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:83)
W/System.err(17491): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(17491): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err(17491): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err(17491): 	at java.lang.Thread.run(Thread.java:764)
E/rtc     (17491):
E/rtc     (17491):
E/rtc     (17491): #
E/rtc     (17491): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
E/rtc     (17491): # last system error: 11
E/rtc     (17491): # Check failed: !env->ExceptionCheck()
E/rtc     (17491): #
I/BufferQueueProducer(17491): [SurfaceTexture-2-17491-1](this:0xc1de6000,id:1,api:4,p:483,c:17491) queueBuffer: slot 1 is dropped, handle=0xe722e860
F/libc    (17491): Fatal signal 6 (SIGABRT), code -6 in tid 18515 (EncoderQueue - ), pid 17491 (p2p_call_sample)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/j7maxlteins/j7maxlte:8.1.0/M1AJQ/G615FXXS2BUD2:user/release-keys'
Revision: '5'
ABI: 'arm'
pid: 17491, tid: 18515, name: EncoderQueue -  >>> com.connectycube.flutter.p2p_call_sample <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    r0 00000000  r1 00004853  r2 00000006  r3 00000008
    r4 00004453  r5 00004853  r6 b0ef5c1c  r7 0000010c
    r8 00000000  r9 00000001  sl 000002d0  fp 00000500
    ip b3dd78d6  sp b0ef5c08  lr f0844c51  pc f083e3ea  cpsr 200d0030
backtrace:
    #00 pc 0001a3ea  /system/lib/libc.so (abort+63)
    #01 pc 0020c5c5  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #02 pc 0020c56d  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #03 pc 001fd1cb  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #04 pc 00321f8b  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #05 pc 00459f7d  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #06 pc 004e6b01  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #07 pc 004e7dad  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #08 pc 004e9f93  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #09 pc 0045d2ab  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #10 pc 0045e1f1  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #11 pc 0045d671  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #12 pc 00212941  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #13 pc 002128b7  /data/app/com.connectycube.flutter.p2p_call_sample-z_ahbOh6Kb7M3juqydMIng==/base.apk (offset 0x19b6000)
    #14 pc 00047f07  /system/lib/libc.so (__pthread_start(void*)+22)
    #15 pc 0001b209  /system/lib/libc.so (__start_thread+32)
Lost connection to device.
Exited (sigterm)
'''

**Comment by denkoul** [comment]
Same problem here

**Comment by amenychtas** [comment]
Confirmed for TCL 20 too.
```
W/System.err(26916): java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Not implemented.
W/System.err(26916):    at java.util.concurrent.FutureTask.report(FutureTask.java:123)
W/System.err(26916):    at java.util.concurrent.FutureTask.get(FutureTask.java:193)
W/System.err(26916):    at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper.initEncode(SimulcastVideoEncoderFactoryWrapper.kt:109)
W/System.err(26916): Caused by: java.lang.UnsupportedOperationException: Not implemented.
W/System.err(26916):    at org.webrtc.WrappedNativeVideoEncoder.initEncode(WrappedNativeVideoEncoder.java:22)
W/System.err(26916):    at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:107)
W/System.err(26916):    at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:83)
W/System.err(26916):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(26916):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(26916):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(26916):    at java.lang.Thread.run(Thread.java:919)
E/rtc     (26916): 
E/rtc     (26916): 
E/rtc     (26916): #
E/rtc     (26916): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
E/rtc     (26916): # last system error: 0
E/rtc     (26916): # Check failed: !env->ExceptionCheck()
E/rtc     (26916): # 
F/libc    (26916): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27537 (EncoderQueue - ), pid 26916 (eleconsultation)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'TCL/T781H_EEA/Irvine:10/QKQ1.200730.002/1A2J:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-11-23 16:49:07+0200
uid: 10344
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  0000000000006b91  x2  0000000000000006  x3  0000007a0b9f9ac0
    x4  feff0df1feff0e67  x5  feff0df1feff0e67  x6  feff0df1feff0e67  x7  7f7f7fff7f7f7f7f
    x8  00000000000000f0  x9  d1996493b858c32a  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
    x16 0000007b5d263738  x17 0000007b5d241bf0  x18 00000079f1384000  x19 0000000000006924
    x20 0000000000006b91  x21 00000000ffffffff  x22 0000007a5720cde3  x23 00000000000001e0
    x24 000000000000012c  x25 000000000000003c  x26 0000000000003196  x27 0000000000000001
    x28 0000000000000001  x29 0000007a0b9f9b60
    sp  0000007a0b9f9aa0  lr  0000007b5d1f3404  pc  0000007b5d1f3430
backtrace:
      #00 pc 0000000000073430  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 1051ed9020715884004db9baaad0de7e)
.....
      #15 pc 00000000000d6b80  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 1051ed9020715884004db9baaad0de7e)
      #16 pc 0000000000074eac  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 1051ed9020715884004db9baaad0de7e)
```

**Comment by mojtabaghiasi** [comment]
same problem 

```
I/OMXClient(15574): IOmx service obtained
I/ACodec  (15574): [OMX.Exynos.VP8.Encoder] Now Loaded
E/org.webrtc.Logging(15574): HardwareVideoEncoder: initEncodeInternal failed
E/org.webrtc.Logging(15574): HardwareVideoEncoder: android.media.MediaCodec$CodecException: Error 0xfffffc0e
E/org.webrtc.Logging(15574): HardwareVideoEncoder: android.media.MediaCodec$CodecException: Error 0xfffffc0e
E/org.webrtc.Logging(15574): 	at android.media.MediaCodec.native_configure(Native Method)
E/org.webrtc.Logging(15574): 	at android.media.MediaCodec.configure(MediaCodec.java:2127)
E/org.webrtc.Logging(15574): 	at android.media.MediaCodec.configure(MediaCodec.java:2043)
E/org.webrtc.Logging(15574): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.configure(MediaCodecWrapperFactoryImpl.java:37)
E/org.webrtc.Logging(15574): 	at org.webrtc.HardwareVideoEncoder.initEncodeInternal(HardwareVideoEncoder.java:260)
E/org.webrtc.Logging(15574): 	at org.webrtc.HardwareVideoEncoder.initEncode(HardwareVideoEncoder.java:220)
E/org.webrtc.Logging(15574): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:107)
E/org.webrtc.Logging(15574): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:83)
E/org.webrtc.Logging(15574): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/org.webrtc.Logging(15574): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/org.webrtc.Logging(15574): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/org.webrtc.Logging(15574): 	at java.lang.Thread.run(Thread.java:923)
W/System.err(15574): java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Not implemented.
W/System.err(15574): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
W/System.err(15574): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
W/System.err(15574): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper.initEncode(SimulcastVideoEncoderFactoryWrapper.kt:109)
W/System.err(15574): Caused by: java.lang.UnsupportedOperationException: Not implemented.
W/System.err(15574): 	at org.webrtc.WrappedNativeVideoEncoder.initEncode(WrappedNativeVideoEncoder.java:22)
W/System.err(15574): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:107)
W/System.err(15574): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:83)
W/System.err(15574): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(15574): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(15574): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(15574): 	at java.lang.Thread.run(Thread.java:923)
E/rtc     (15574): #
E/rtc     (15574): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
E/rtc     (15574): # last system error: 0
E/rtc     (15574): # Check failed: !env->ExceptionCheck()
E/rtc     (15574): # 
F/libc    (15574): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20528 (EncoderQueue - ), pid 15574 (livekit.example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/y2sxx/y2s:11/RP1A.200720.012/G985FXXSCDUK2:user/release-keys'
Revision: '22'
ABI: 'arm64'
Timestamp: 2021-11-30 13:48:56+0330
pid: 15574, tid: 20528, name: EncoderQueue -  >>> io.livekit.example <<<
uid: 10349
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  0000000000005030  x2  0000000000000006  x3  000000720126d8b0
    x4  fefefefffefeff2f  x5  fefefefffefeff2f  x6  fefefefffefeff2f  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  e9b94537ea191a79  x10 0000000000000000  x11 ffffffc0fffffbdf
    x12 0000000000000001  x13 00000000000000c2  x14 0000000000000000  x15 000057f67ac3de16
    x16 00000075b57ffc80  x17 00000075b57e1d50  x18 000000720014e000  x19 0000000000003cd6
    x20 0000000000005030  x21 00000000ffffffff  x22 000000721db5dde3  x23 00000000000000f0
    x24 000000000000007d  x25 000000000000000f  x26 0000000000002ff6  x27 0000000000000000
    x28 0000000000000000  x29 000000720126d930
    lr  00000075b5795724  sp  000000720126d890  pc  00000075b5795750  pst 0000000000001000
backtrace:
      #00 pc 000000000004e750  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 47fa1511afbec3da8219bfec53725f93)
      #01 pc 0000000000387c50  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #02 pc 0000000000387be8  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #03 pc 000000000036f688  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #04 pc 000000000036f5ac  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #05 pc 0000000000516dd4  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #06 pc 000000000051b764  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #07 pc 000000000051af00  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #08 pc 00000000006ba760  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #09 pc 000000000078b5e8  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #10 pc 000000000078cfc4  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #11 pc 000000000078ff0c  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #12 pc 00000000006bf2a4  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #13 pc 00000000006c0954  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #14 pc 00000000006bf8a4  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #15 pc 00000000003917fc  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #16 pc 0000000000391704  /data/app/~~xapS6rSglVMnDJUBLOK2tQ==/io.livekit.example-MxodN8SWB5QlMX3ymPURFA==/lib/arm64/libjingle_peerconnection_so.so (BuildId: bc662912e660ccb2)
      #17 pc 00000000000b0228  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 47fa1511afbec3da8219bfec53725f93)
      #18 pc 000000000005070c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 47fa1511afbec3da8219bfec53725f93)
```

**Comment by cloudwebrtc** [comment]
Please upgrade to the latest version.  If the problem persists, please reopen this issue.
