### ISSUE TITLE
There is problem on android

### ISSUE THREAD

**Issue by Davud44** [flutter-webrtc/flutter-webrtc#805]
crash with error:

E/AndroidRuntime( 6546): java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler org.webrtc.SurfaceTextureHelper.getHandler()' on a null object reference
E/AndroidRuntime( 6546): 	at org.webrtc.CameraCapturer.initialize(CameraCapturer.java:241)
E/AndroidRuntime( 6546): 	at org.webrtc.Camera1Capturer.initialize(Camera1Capturer.java:15)
E/AndroidRuntime( 6546): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserVideo(GetUserMediaImpl.java:685)
E/AndroidRuntime( 6546): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:549)
E/AndroidRuntime( 6546): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.access$000(GetUserMediaImpl.java:82)
E/AndroidRuntime( 6546): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl$1.invoke(GetUserMediaImpl.java:408)
E/AndroidRuntime( 6546): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.lambda$requestPermissions$0(GetUserMediaImpl.java:767)
E/AndroidRuntime( 6546): 	at com.cloudwebrtc.webrtc.-$$Lambda$GetUserMediaImpl$AYlbN-lau_BtO18rLwHpvrTF91U.invoke(lambda)
E/AndroidRuntime( 6546): 	at com.cloudwebrtc.webrtc.utils.PermissionUtils$1.onReceiveResult(PermissionUtils.java:115)
E/AndroidRuntime( 6546): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime( 6546): 	at android.os.Handler.handleCallback(Handler.java:754)
E/AndroidRuntime( 6546): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6546): 	at android.os.Looper.loop(Looper.java:163)
E/AndroidRuntime( 6546): 	at android.app.ActivityThread.main(ActivityThread.java:6238)
E/AndroidRuntime( 6546): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6546): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
E/AndroidRuntime( 6546): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by jdwxp** [comment]
I have the same problem,I find It's triggered when you switch the camera too many times

**Comment by ycherniavskyi** [comment]
Please mention you SDK and plugin version in such type of issues.

How did you call `getUserMedia` from Dart side?

Have you try to look in [webrtc](https://github.com/webrtc-sdk/webrtc) to understand the possible reason of the exception?

**Comment by jdwxp** [comment]
as shown in the figure

![image](https://user-images.githubusercontent.com/22138796/182108648-a05e7ad4-9003-4078-8ffe-08c4ad24d11d.png)

when  switch the camera ,  `videoCapturer.initialize(
                surfaceTextureHelper, applicationContext, videoSource.getCapturerObserver());` is executed , but sometime ,`surfaceTextureHelper`     could be create failed, I printed the log as shown below

![image](https://user-images.githubusercontent.com/22138796/182108198-0440aae3-2c22-4686-b3b0-ed9cce45927a.png)

![image](https://user-images.githubusercontent.com/22138796/182108251-a14958a7-6b07-4c23-a599-06db1ced011e.png)
