### ISSUE TITLE
MediaDevices.getUserMedia() fails when requesting Camera on macos

### ISSUE THREAD

**Issue by renjipanicker** [flutter-webrtc/flutter-webrtc#837]
On MacOS, any call to MediaDevices.getUserMedia() fails when video is requested. It works correctly when only audio is requested.
Things I have checked so far:
1. Have add NSCameraUsageDescription to the macos/Runner/Info.plist file.
2. Have run the app from the command line and from VSCode debug
3. If I reset all permissions (using tccutil), then either terminal or vscode (depending on where I have run it from) asks for permission to use Microphone, but not Camera. Neither Terminal or VScode appears in the list of apps requesting/requested permissions for Camera.

**To Reproduce**
The following is a minimal code to reproduce the error.
```
import 'package:flutter/material.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _onPress,
        tooltip: 'Connect',
        child: const Icon(Icons.add),
      ),
    );
  }

  Future<void> _onPress() async {
    await _makeCall({'audio': false,'video': false});
    await _makeCall({'audio': false,'video': true });
    await _makeCall({'audio': true, 'video': false});
    await _makeCall({'audio': true, 'video': true });
  }

  Future<void> _makeCall(final Map<String,dynamic> mediaConstraints) async {
    print("Connecting with $mediaConstraints");
    var devs = await navigator.mediaDevices.enumerateDevices();
    print("${devs.length}");
    for(var dev in devs) {
      print("${dev.deviceId}: ${dev.kind}/${dev.label}");
    }

    try{
      var stream = await navigator.mediaDevices.getUserMedia(mediaConstraints);
      print("Success\n");
    }catch(ex,st) {
      print("Exception: $ex\n$st\n");
    }
  }
}

```
**Expected behavior**
The call to getUserMedia should succeed. Instead this is the observed result:
```
renji@nalanda webrtc01 % flutter run -d macos    
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                           1,304ms
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:52369163-7A84-56F8-8D67-E4812D0EC191 }
{ platform:macOS, name:Any Mac }
Building macOS application...                                           
Syncing files to device macOS...                                   105ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:56966/CKLZViIaMAw=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:56966/CKLZViIaMAw=/
flutter: Connecting with {audio: false, video: false}
flutter: 0
flutter: Success

flutter: Connecting with {audio: false, video: true}
flutter: 0
flutter: Exception: Unable to getUserMedia: NotFoundError
#0      MediaDeviceNative.getUserMedia (package:flutter_webrtc/src/native/mediadevices_impl.dart:29:7)
<asynchronous suspension>
#1      _MyHomePageState._makeCall (package:webrtc01/main.dart:65:20)
<asynchronous suspension>
#2      _MyHomePageState._onPress (package:webrtc01/main.dart:51:5)
<asynchronous suspension>


flutter: Connecting with {audio: true, video: false}
flutter: 0
flutter: Success

flutter: Connecting with {audio: true, video: true}
flutter: 0
flutter: Exception: Unable to getUserMedia: NotFoundError
#0      MediaDeviceNative.getUserMedia (package:flutter_webrtc/src/native/mediadevices_impl.dart:29:7)
<asynchronous suspension>
#1      _MyHomePageState._makeCall (package:webrtc01/main.dart:65:20)
<asynchronous suspension>
#2      _MyHomePageState._onPress (package:webrtc01/main.dart:53:5)
<asynchronous suspension>

```

**Platform information**

* **Flutter version**: 
```
renji@nalanda webrtc01 % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/renji/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!

```
* **Plugin version**:
0.8.1

* **OS**: 
MacOS

* **OS version**:
Monterrey 12.1

**Comment by shubhamsinghshubham777** [comment]
@renjipanicker Can you please mention how were you able to resolve it?

**Comment by kunjaarogyatech** [comment]
@renjipanicker Can you please mention how were you able to resolve it?

**Comment by ardeshir-33033** [comment]
@shubhamsinghshubham777 
@kunjaarogyatech 
You have to add these two rows in the Debug.Entitlements and Release.Entitlements files which exists in path: macos/runner

<key>com.apple.security.device.audio-input</key>
<true/>
<key>com.apple.security.device.camera</key>
<true/>

hope this helps.
