### ISSUE TITLE
Error: UnimplementedError Flutter WEB

### ISSUE THREAD

**Issue by Hamzadildar** [flutter-webrtc/flutter-webrtc#844]
Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:58522/dart_sdk.js:5063:11)
    at Function.getCallbackHandle (http://localhost:58522/dart_sdk.js:138816:17)
    at initialize (http://localhost:58522/packages/flutter_downloader/src/downloader.dart.lib.js:77:58)
    at initialize.next (<anonymous>)
    at runBody (http://localhost:58522/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:58522/dart_sdk.js:40242:7)
    at Function.initialize (http://localhost:58522/packages/flutter_downloader/src/downloader.dart.lib.js:74:20)
    at main$ (http://localhost:58522/packages/daxssapp/main.dart.lib.js:319:42)
    at main$.next (<anonymous>)
    at runBody (http://localhost:58522/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:58522/dart_sdk.js:40242:7)
    at main$ (http://localhost:58522/packages/daxssapp/main.dart.lib.js:316:18)
    at main (http://localhost:58522/web_entrypoint.dart.lib.js:36:29)
    at main.next (<anonymous>)
    at http://localhost:58522/dart_sdk.js:40192:33
    at _RootZone.runUnary (http://localhost:58522/dart_sdk.js:40062:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:58522/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:58522/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:58522/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:58522/dart_sdk.js:35437:23)
    at http://localhost:58522/dart_sdk.js:34617:46
    at _RootZone.runUnary (http://localhost:58522/dart_sdk.js:40062:59)
    at _FutureListener.then.handleValue (http://localhost:58522/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:58522/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:58522/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:58522/dart_sdk.js:35437:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58522/dart_sdk.js:35458:35)
    at Object._microtaskLoop (http://localhost:58522/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:58522/dart_sdk.js:40336:13)
    at http://localhost:58522/dart_sdk.js:35811:9

_Originally posted by @Hamzadildar in https://github.com/flutter-webrtc/flutter-webrtc/issues/576#issuecomment-1026734031_

**Comment by cloudwebrtc** [comment]
The error you're running appears to be thrown from a minified dart2js library, I think you can run in debug mode and reproduce the error, so you can locate the real dart line of code.

**Comment by cloudwebrtc** [comment]
Please update to the latest stable channel.
