### ISSUE TITLE
Unhandled Exception: type 'int' is not a subtype of type 'String' on iOS 14.4.2

### ISSUE THREAD

**Issue by http600** [flutter-webrtc/flutter-webrtc#923]
**What Happened**
1. Exception as bellow
2. ANR
```
2022-04-20 21:30:14.257602+0800 Runner[1725:382025] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'int' is not a subtype of type 'String'
#0      RTCDataChannelNative.eventListener (package:flutter_webrtc/src/native/rtc_data_channel_impl.dart:54:42)
#1      _rootRunUnary (dart:async/zone.dart:1434:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#8      _rootRun (dart:async/zone.dart:1418:47)
#9      _CustomZone.run (dart:async/zone.dart:1328:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#12     _rootRun (dart:async/zone.dart:1426:13)
#13     _CustomZone.run (dart:async/zone.dart:1328:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
**To Reproduce**
Install App developed based on flutter-webrtc
**Expected behavior**
Do not throw exception and do not hangs
**Platform information**

* **Flutter version**: 
  ```
  flutter doctor
  Doctor summary (to see all details, run flutter doctor -v):
  [✓] Flutter (Channel stable, 2.10.4, on macOS 11.4 20F71 darwin-x64, locale en-CN)
  [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
  [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
  [✓] Chrome - develop for the web
  [✓] Android Studio (version 2021.1)
  [✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
  [✓] VS Code (version 1.66.2)
  [✓] Connected device (2 available)
      ! Error: iPhoneOfLegend is not connected. Xcode will continue when iPhoneOfLegend is connected. (code -13)
      ! Error: iPhoneOfMiracle is busy: Fetching debug symbols for iPhoneOfMiracle. Xcode will continue when iPhoneOfMiracle is finished. (code -10)
  ⢿^C%                                                                                                                                                                            ➜  ~ flutter doctor -v
  [✓] Flutter (Channel stable, 2.10.4, on macOS 11.4 20F71 darwin-x64, locale en-CN)
      • Flutter version 2.10.4 at /Users/2infinity/Downloads/workspace/flutter_projects/sample/flutter
      • Upstream repository https://github.com/flutter/flutter.git
      • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
      • Engine revision 57d3bac3dd
      • Dart version 2.16.2
      • DevTools version 2.9.2
  
  [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
      • Android SDK at /Users/2infinity/Library/Android/sdk
      • Platform android-31, build-tools 33.0.0-rc1
      • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
      • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
      • All Android licenses accepted.
  
  [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
      • Xcode at /Applications/Xcode.app/Contents/Developer
      • CocoaPods version 1.11.2
  
  [✓] Chrome - develop for the web
      • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  
  [✓] Android Studio (version 2021.1)
      • Android Studio at /Applications/Android Studio.app/Contents
      • Flutter plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/9212-flutter
      • Dart plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/6351-dart
      • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
  
  [✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
      • IntelliJ at /Applications/IntelliJ IDEA.app
      • Flutter plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/9212-flutter
      • Dart plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/6351-dart
  
  [✓] VS Code (version 1.66.2)
      • VS Code at /Applications/Visual Studio Code.app/Contents
      • Flutter extension version 3.38.1
  
  [✓] Connected device (2 available)
      • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
      • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127
      ! Error: iPhoneOfLegend is not connected. Xcode will continue when iPhoneOfLegend is connected. (code -13)
      ! Error: iPhoneOfMiracle is busy: Fetching debug symbols for iPhoneOfMiracle. Xcode will continue when iPhoneOfMiracle is finished. (code -10)
  
  [!] HTTP Host Availability
      ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed out
      ✗ HTTP host https://cloud.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed out
  
  ! Doctor found issues in 1 category.

  ```
* **Plugin version**:  flutter-webrtc 0.8.5
* **OS**:  iOS
* **OS version**: 14.4.2

**Comment by http600** [comment]
I'm not sure this is the same to #910 or not, I noticed that one was Android and Windows, but this is iOS, one more thing this is not reproducing on **`iOS 12.5.5`**
